---
title: "TidyTuesday 2019/22 - Wine Ratings by Vivino"
author: "Cedric Scherer"
date: "28th of May 2019"
output:
  html_document:
    theme: paper
    highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r prep, message=FALSE, warning=FALSE}
## packages
library(tidyverse)
library(patchwork)

## ggplot theme updates
source("./theme/tidy_grey.R")
```

```{r data}
df_wines <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-28/winemag-data-130k-v2.csv") %>% 
  dplyr::select(-X1) %>% 
  unique()
```

```{r plot}
img_b <- png::readPNG("./img/bottle.png") 
bottle <- grid::rasterGrob(img_b, interpolate = T) 

bottles <- df_wines %>% 
  group_by(country) %>% 
  summarize(
    rating = mean(points, na.rm = T),
    n = n()
  ) %>% 
  ungroup() %>% 
  mutate(
    rating = (rating - 80) / 20,
    country = ifelse(country == "New Zealand", "New\nZealand", country),
    country = ifelse(country == "South Africa", "South\nAfrica", country),
    country = fct_reorder(country, -rating)
  ) %>% 
  filter(!is.na(country), n > 99) %>% 
  ggplot(aes(country, rating)) +
    geom_col(width = 11.5, fill = "#770000") +
    annotation_custom(bottle, xmin = -19.5, xmax = 20.5, ymin = -0.03, ymax = 1.3) +
    facet_wrap(~ country, nrow = 1, scales = "free_x", strip.position = "bottom") +
    scale_x_discrete(expand = c(10, 10)) +
    scale_y_continuous(limits = c(0, 1.3), breaks = seq(0, 1, by = 0.25), 
                       labels = c("80", "85", "90", "95", "100")) +
    theme(plot.caption = element_text(size = 9),
          axis.title.y = element_text(size = 12, hjust = 0.2),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 7, family = "Roboto Mono"),
          axis.ticks = element_blank(),
          strip.background = element_rect(color = NA),
          strip.text = element_text(size = 9, face = "plain", vjust = 1),
          panel.border = element_rect(color = NA),
          panel.grid.major.y = element_line(color = "grey30"),
          panel.spacing = unit(0, "lines")) +
  labs(x = NULL, y = "Rating", 
       caption = "\nVisualization by @CedScherer  |  Data source: Kaggle")

## left-alligned title
title <- ggplot(data.frame(x = 1:2, y = 1:10)) +
  labs(x = NULL, y = NULL,
       title = "The best wines you can get.",
       subtitle = "Average score on Vivino for countries with \u2265 100 wines (based on reviews with \u2265 80 points).\n") +
  theme(line = element_blank(),
        plot.background = element_rect(fill = "transparent", color = "transparent"),
        #plot.title = element_text(size = 18),
        panel.background = element_rect(fill = "transparent"),
        panel.border = element_rect(color = "transparent"),
        axis.text = element_blank())

title + bottles + plot_layout(widths = c(0, 3))

ggsave("./plots/2019_22/2019_22_Wines.pdf", width = 14, height = 2.67, device = cairo_pdf)
```

***

```{r}
sessionInfo()
```
