---
title: "TidyTuesday 2019/50 - Replicating Plots in R by Simply Statistics"
author: "Cedric Scherer"
date: "13th of December 2019"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep, message=FALSE, warning=FALSE}
## packages
library(tidyverse)
library(ggtext)
library(ggforce)
library(extrafont)

## ggplot theme
source(here::here("R", "tidy_grey.R"))

extrafont::loadfonts()

theme_update(rect = element_rect(fill = "#f7f7f7"),
             text = element_text(family = "Ebrima"),
             axis.text.x = element_markdown(),
             axis.text.y = element_blank(),
             axis.title = element_blank(),
             axis.ticks = element_blank(),
             panel.border = element_blank())
```

## Inspiration

Original plots: https://pudding.cool/projects/vocabulary/
Data: https://docs.google.com/spreadsheets/d/1HIIfgDpNMM-j0hoQHN-yP5P1lNOfJuvym0u0sdWwD9g/edit#gid=737896402

```{r data}
df_rap <- readr::read_csv(here::here("data", "2019_50", "HipHop_VocabChart_full.csv"))

df_rap_clean <-
  df_rap %>%
  mutate(notes = if_else(is.na(notes), "none", notes)) %>%
  filter(
    !is.na(era),
    !is.na(recalc),
    notes != "remove"
  )
```

```{r plot-1, fig.width = 20, fig.height = 11.3}
df_rap_1 <-
  df_rap_clean %>%
  mutate(
    words_lmd = if_else(recalc > 6500, recalc - 400, recalc),
    height = 1
  )

df_line <-
  tibble(
    words_lmd = c(2472, 6650, 6675, 6725, 6750, 7479),
    height = c(1, 1, 1.005, 0.997, 1, 1)
  )

labs1 <- c("**3,000** words", "**4,000**", "**5,000**", "**6,000** words")

df_rap_1  %>%
  ggplot(aes(height, words_lmd)) +
    geom_path(data = df_line, aes(height, words_lmd), size = 1.6) +
    geom_mark_circle(data = df_rap_1 %>% filter(recalc > 6500 | recalc < 2500),
                     aes(group = rapper_clean,
                         label = glue::glue("{rapper_clean}:"),
                         description = glue::glue("{recalc} unique words")),
                     color = NA,
                     label.colour = "#333333",
                     label.fill = "grey93",
                     con.colour = "#333333",
                     con.cap = -3) +
    ggbeeswarm::geom_beeswarm(aes(fill = era),
                              groupOnX = T,
                              size = 9.2,
                              shape = 21,
                              color = "#333333",
                              priority = "random",
                              cex = 3.7) +
    annotate("text", x = 1.008, y = 6900,
             label = "7,300\nwords",
             family = "Ebrima",
             lineheight = 0.8,
             size = 4.7,
             hjust = 0.5) +
    coord_flip() +
    scale_x_continuous(limits = c(0.94, 1.06),
                       expand = c(0, 0)) +
    scale_y_continuous(position = "right",
                       labels = labs1,
                       breaks = seq(3000, 6000, by = 1000)) +
    scale_fill_manual(values = c("grey75", "grey60", "grey45", "grey30"),
                      na.value = "white") +
    guides(fill = guide_legend(nrow = 1,
                               label.position = "right",
                               override.aes = list(size = 6.5))) +
    labs(title = "# of Unique Words Used Within Artist's First 35,000 Lyrics",
         caption = "        Notes/sources:\n\n        All lyrics are via Genius.\n\n        Original visualization by Matt Daniels\n        Replicated in R by Cédric Scherer") +
    theme(panel.grid.major.x = element_line(color = "black",
                                            size = 0.2,
                                            linetype = "dotted"),
          axis.text.x.top = element_markdown(color = "black",
                                             size = 18),
          plot.title = element_text(color = "#333333",
                                    size = 35,
                                    face = "plain",
                                    hjust = 0.5,
                                    margin = margin(t = 40, b = 40)),
          plot.caption = element_text(color = "#333333",
                                      size = 11,
                                      lineheight = 1.3,
                                      hjust = 0,
                                      margin = margin(t = 15, b = 15)),
          legend.position = c(0.82, 0.05),
          legend.key = element_rect(color = NA,
                                    fill = NA),
          legend.title = element_blank(),
          legend.text = element_text(color = "#333333",
                                     size = 15))

ggsave(here::here("plots", "2019_50", "2019_50_Replicate_Rap_bee.pdf"),
       width = 20, height = 11.3, device = cairo_pdf)
```

```{r plot-2, fig.width = 13.5, fig.height = 9}
df_rap_2 <-
  df_rap_clean %>%
  mutate(
    words = recalc,
    words_bins = case_when(
      words < 2750 ~ "<2,750",
      words >= 2750 & words < 3200 ~ "2,750–3,200",
      words >= 3200 & words < 3650 ~ "3,200–3,650",
      words >= 3650 & words < 4100 ~ "3,650–4,100",
      words >= 4100 & words < 4550 ~ "4,100–4,550",
      words >= 4550 & words < 5000 ~ "4,550–5,000",
      words >= 5000 & words < 5450 ~ "5,000–5,450",
      words >= 5450 & words < 5900 ~ "5,450–5,900",
      words >= 5900 & words < 6350 ~ "5,900–6,350",
      words >= 6350 ~ "6,350+",
      TRUE ~ ""
    ),
    words_fct = factor(words_bins,
                       levels = c("<2,750",
                                  "2,750–3,200",
                                  "3,200–3,650",
                                  "3,650–4,100",
                                  "4,100–4,550",
                                  "4,550–5,000",
                                  "5,000–5,450",
                                  "5,450–5,900",
                                  "5,900–6,350",
                                  "6,350+")),
    rapper_short = if_else(nchar(rapper_clean) > 15,
                           glue::glue("{str_sub(rapper_clean, start = 1, end = 12)}..."),
                           glue::glue("{rapper_clean}"))
  )


labs2 <- glue::glue("<b style='font-size:12pt'>{as.character(levels(df_rap_2$words_fct))}</b><br><span style='font-size:08pt'>unique words</span>")

df_rap_2 %>%   
  group_by(words_fct) %>%
  arrange(desc(era), desc(rapper_clean)) %>%
  mutate(rank = row_number()) %>%
  ggplot(aes(words_fct, rank)) +
    geom_hline(yintercept = 0.25,
               size = 0.1) +
    geom_vline(xintercept = seq(0.5, 9.5, by = 1),
               color = "#f7f7f7",
               size = 5) +
    geom_text(aes(label = rapper_short,
                  color = era),
              size = 3.7,
              hjust = 0,
              nudge_x = -0.45,
              family = "Ebrima") +
    annotate("text",
             x = 9, y = 29,
             label = "# of Unique Words\nUsed Within Artist's\nFirst 35,000 Lyrics",
             lineheight = 1.05,
             size = 9,
             hjust = 0.5,
             family = "Ebrima",
             color = "#333333") +
    annotate("text",
             x = 9, y = 23.8,
             label = "BY ERA¹",
             size = 4.2,
             hjust = 0.5,
             family = "Ebrima",
             color = "grey66") +
    geom_richtext(x = 9, y = 22,
                  fill = NA,
                  label.color = NA,
                  label = "<span style='color:#b14cda'>1980s</span> | <span style='color:#44909c'>1990s</span> | <span style='color:#2045f6'>2000s</span> | <span style='color:#ce302b'>2010s</span>",
                  size = 5.5,
                  color = "grey66",
                  hjust = 0.5,
                  family = "Ebrima") +
    scale_x_discrete(expand = c(0.05, 0.05),
                     labels = labs2) +
    scale_y_continuous(limits = c(0.18, 32.5),
                       expand = c(0, 0)) +
    scale_color_manual(values = c("#b14cda", "#44909c", "#2045f6", "#ce302b"),
                       guide = F) +
    labs(caption = "Notes/sources:<br><br>(1) Since this analysis uses an artist’s first 35,000 lyrics<br>(prioritizing studio albums), an artist’s era is determined by<br>        the years the albums were released. Some artists may be<br>identified with a certain era (for example, Jay-Z with the<br>1990s, with <i>Reasonable Doubt</i> in 1996, <i>In My Lifetime, Vol. 1</i><br>in 1997, etc.) yet continue to release music in the present day.<br><br>All lyrics are via Genius.<br><br>Original visualization by Matt Daniels<br>Replicated in R by Cédric Scherer") +
    theme(axis.text.x = element_markdown(color = "#333333",
                                         hjust = 0.5,
                                         size = 8), ## to adjust lineheight
          plot.caption = element_markdown(color = "#333333",
                                          size = 10.5,
                                          lineheight = 1.3,
                                          hjust = 0,
                                          margin = margin(30, 0, 20, 20)),
          plot.margin = margin(10, 20, 10, 20))

ggsave(here::here("plots", "2019_50", "2019_50_Replicate_Rap_text.pdf"),
       width = 12.6, height = 10, device = cairo_pdf)
```

***

```{r session-info}
sessionInfo()
```
