---
title: "TidyTuesday 2019/20 - Nobel Prize Winners by Harvard Dataverse"
author: "Cedric Scherer"
date: "14th of May 2019"
output:
  html_document:
    theme: paper
    highlight: kate
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r prep, message=FALSE}
## packages
library(tidyverse)
library(scico)
library(emojifont)
library(showtext)
library(patchwork)

## ggplot theme updates
source(here::here("R", "tidy_grey.R"))

## add fonts via showtext (extrafont and emojifont do not worl together)
font_add_google("Poppins", "Poppins")
font_add_google("Roboto Mono", "Roboto Mono")
showtext_auto()
```

```{r data}
df_nobel <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-14/nobel_winners.csv")
```

```{r plot, fig.width = 14, fig.height = 5.5}
## tile plot facetted by gender
tile_gender <- df_nobel %>% 
  filter(laureate_type == "Individual") %>% 
  mutate(decade = glue::glue("{round(prize_year - 1, -1)}s")) %>% 
  group_by(decade, category) %>% 
  mutate(ind_awards = n()) %>%
  group_by(decade, category, gender) %>% 
  summarize(prop = n() / unique(ind_awards)) %>%  
  ungroup() %>% 
  complete(decade, category, gender, fill = list(prop = 0)) %>% 
  group_by(decade, category) %>% 
  mutate(
    prop_fem = min(prop),
    prop_male = max(prop)
  ) %>% 
  group_by(category) %>% 
  mutate(avg_fem = mean(prop_fem)) %>% 
  ungroup() %>% 
  mutate(
    label = if_else(gender == "Male", fontawesome("fa-mars"), 
                                      fontawesome("fa-venus")),
    category = fct_reorder(category, avg_fem),
    prop = if_else((prop_fem + prop_male) == 0, NA_real_, prop)
  ) %>% 
  ggplot(aes(decade, category, color = prop, label = label)) +
    geom_tile(fill = "grey25", color = "grey20", size = 0.7) +
    geom_text(family = 'fontawesome-webfont', size = 8) +
    facet_grid(. ~ gender) +
    scale_color_scico(palette = "buda", name = NULL, na.value = "grey25",
                      guide = guide_colorbar(direction = "horizontal",
                                             barheight = unit(3, units = "mm"), 
                                             barwidth = unit(150, units = "mm"),
                                             draw.ulim = FALSE, title.position = 'bottom',
                                             title.hjust = 0.5, label.hjust = 0.5)) +
    theme(strip.text = element_blank(),
          panel.spacing.x = unit(15, "pt"),
          axis.text.x = element_text(family = "Roboto Mono", size = 9),
          legend.position = "bottom",
          axis.ticks = element_blank(),
          panel.border = element_rect(color = "grey20")) + 
    labs(x = NULL, y = NULL,
         caption = '\nVisualization by Cédric Scherer  |  Data: Harvard Dataverse, Li et al. 2018, doi: 10.7910/DVN/6NJ5RN')
```

```{r title}
## left-alligned title
title <- ggplot(data.frame(x = 1:2, y = 1:10)) +
  labs(x = NULL, y = NULL,
       title = 'The male dominance of the Nobel prize',
       subtitle = "Proportion of female and male Nobel prize winners per category and decade.\n") +
  theme(line = element_blank(),
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = "transparent"),
        panel.border = element_rect(color = "transparent"),
        axis.text = element_blank())
```

```{r full-panel, fig.width = 14, fig.height = 5.5}
## full panel
title + tile_gender + plot_layout(width = c(0, 1))

ggsave(here::here("plots", "2019_20", "2019_20_NobelPrizeWinners.pdf"), 
       width = 14, height = 5.2, device = cairo_pdf)
```

***

```{r session}
sessionInfo()
```
