---
title: "TidyTuesday 2019/38 - US National Park Visits by data.world"
author: "Cedric Scherer"
date: "4th of November 2019"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep, message=FALSE, warning=FALSE}
## packages
library(tidyverse)
library(geojsonio)
library(broom)
library(rgeos)
library(patchwork)
library(showtext)

font_add_google("Lobster", "Lobster")
font_add_google("Montserrat", "Montserrat")
font_add_google("Roboto Mono", "Roboto Mono")

## ggplot theme updates
theme_set(theme_bw(base_family = "Lobster"))

theme_update(rect = element_rect(fill = "#e8d8c3",
                                 color = "#e8d8c3"),
             panel.grid.major = element_blank(),
             panel.grid.minor = element_blank(),
             panel.background = element_rect(fill = "#e8d8c3",
                                             color = NA),
             panel.border = element_blank(),
             plot.background = element_rect(fill = "#e8d8c3",
                                            color = "#e8d8c3"),
             axis.ticks = element_blank(),
             axis.text = element_blank(),
             axis.title = element_blank(),
             legend.position = c(0.5, 0.875),
             legend.title = element_text(size = 13),
             legend.text = element_text(family = "Montserrat"),
             plot.title = element_text(size = 30,
                                       face = "bold",
                                       hjust = 0.5,
                                       margin = margin(t = 10, b = 0)),
             plot.subtitle = element_text(size = 18,
                                          color = "grey55",
                                          face = "bold",
                                          hjust = 0.5,
                                          margin = margin(t = 0, b = 15)),
             plot.caption = element_text(size = 12,
                                         color = "grey55",
                                         hjust = 0.5,
                                         margin = margin(t = 15, b = 10)))
```

```{r}
df_nps <-
  readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-17/national_parks.csv")

df_states <-
  readr::read_csv(here::here("data", "2019_38", "50_us_states_all_data.csv"),
                  col_names = F) %>%
  dplyr::select(state = "X2", ISO2 = "X3")%>%
  add_row(state = "District of Colombia", ISO2 = "DC")
```

```{r}
map_hex <- geojson_read(here::here("data", "2019_38", "us_states_hexgrid.geojson.json"),  what = "sp")

map_hex@data <-
  map_hex@data %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))

## fortify
map_hex_fortified <- tidy(map_hex, region = "google_name")

## centroids for labels
centroids <- cbind.data.frame(data.frame(gCentroid(map_hex, byid = T),
                                         id = map_hex@data$iso3166_2,
                                         id_long = str_wrap(map_hex@data$google_name, 12)))

## number of NPs and visitors since 2010
df_nps_sum <-
  df_nps %>%
  mutate(year = as.numeric(year)) %>%
  filter(year > 1999) %>%
  group_by(state) %>%
  replace_na(list(visitors = 0)) %>%
  summarize(
    n = n_distinct(unit_name),
    visitors = sum(visitors, na.rm = T),
    visitors_m = if_else(!is.na(visitors), visitors / 1000000, 0),
    prop = if_else(n > 0, visitors_m / n, 0)
  )

## change of visitor rates 90s versus 10s
df_nps_change <-
  df_nps %>%
  mutate(decade = year %/% 10 * 10) %>%
  filter(decade %in% c(1990, 2000)) %>%
  group_by(decade, state) %>%
  summarize(visitors = sum(visitors, na.rm = T)) %>%
  pivot_wider(names_from = decade, values_from = visitors) %>%
  mutate(change = (`2000` / `1990`), change_log = log2(change))

## combine data
df_nps_hex <-
  map_hex_fortified %>%
  left_join(df_states, by = c("id" = "state")) %>%
  left_join(df_nps_sum, by = c("ISO2" = "state")) %>%
  left_join(df_nps_change, by = c("ISO2" = "state"))
```

```{r}
hex_nps <-
  df_nps_hex %>%
  replace_na(list(n = 0)) %>%
  ggplot() +
    geom_polygon(aes(long, lat,
                     group = group,
                     fill = n),
                 color = "white") +
    geom_text(data = centroids,
              aes(x = x, y = y + 0.35, label = id),
              family = "Montserrat",
              fontface = "bold") +
    geom_text(data = centroids,
              aes(x = x, y = y - 0.3, label = id_long),
              family = "Montserrat",
              color = "grey30",
              fontface = "bold",
              size = 1.5,
              lineheight = 0.8,
              vjust = 1) +
    coord_map() +
    rcartocolor::scale_fill_carto_c(palette = "PinkYl",
                                    name = "Number of National Parks",
                                    limits = c(0, NA),
                                    breaks = c(0, seq(5, 25, by = 5))) +
    guides(fill = guide_colorbar(barheight = unit(3, units = "mm"),  
                                 barwidth = unit(80, units = "mm"),
                                 direction = "horizontal",
                                 ticks.colour = "#e8d8c3",
                                 title.position = "top",
                                 title.hjust = 0.5)) +
    labs(title = "US National Parks by States",
         subtitle = "Where to find them and how visitor numbers have changed since the 1990s")

hex_visits <-
  ggplot(df_nps_hex) +
    geom_polygon(aes(long, lat,
                     group = group,
                     fill = visitors_m),
                 color = "white") +
    geom_text(data = centroids,
              aes(x = x, y = y, label = id),
              family = "Montserrat",
              color = "grey50",
              fontface = "bold") +
    coord_map() +
    rcartocolor::scale_fill_carto_c(palette = "Emrld",
                                    name = "Number of Visitors since 2000 (in millions)",
                                    limits = c(NA, 600),
                                    breaks = seq(100, 600, by = 100)) +
    guides(fill = guide_colorbar(barheight = unit(3, units = "mm"),  
                                 barwidth = unit(80, units = "mm"),
                                 direction = "horizontal",
                                 ticks.colour = "#e8d8c3",
                                 title.position = "top",
                                 title.hjust = 0.5))

hex_change <-
  ggplot(df_nps_hex) +
    geom_polygon(aes(long, lat,
                     group = group,
                     fill = change_log),
                 color = "white") +
    geom_text(data = centroids,
              aes(x = x, y = y, label = id),
              family = "Montserrat",
              color = "grey50",
              fontface = "bold") +
    coord_map() +
    rcartocolor::scale_fill_carto_c(palette = "Temps",
                                    name = "Change in Visitor Numbers (1990s to 2000s)",
                                    direction = -1,
                                    limits = c(-2, 2),
                                    breaks = seq(-2, 2, by = 1),
                                    labels = c("25%", "50%", "100%", "200%", "400%")) +
    guides(fill = guide_colorbar(barheight = unit(3, units = "mm"),  
                                 barwidth = unit(80, units = "mm"),
                                 direction = "horizontal",
                                 ticks.colour = "#e8d8c3",
                                 title.position = "top",
                                 title.hjust = 0.5)) +
    labs(caption = "Visualization by Cédric Scherer  ∙  Data by data.world via Jack King")
```

```{r full-panel}
hex_nps / plot_spacer() / hex_visits / plot_spacer() / hex_change +
  plot_layout(heights = c(1, 0.05, 1, 0.05, 1))

ggsave(here::here("plots", "2019_38", "2019_38_NationalParks.pdf"),
       width = 8, height = 16.5, device = cairo_pdf)
```

***

```{r session-info}
sessionInfo()
```
