---
title: "TidyTuesday 2019/39 - School Diversity by NCES"
author: "Cedric Scherer"
date: "25th of September 2019"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep, message=FALSE, warning=FALSE}
## packages
library(tidyverse)
library(ggbeeswarm)
library(biscale)
library(fiftystater)
library(geofacet)
library(patchwork)
library(cowplot)
library(ggtext)

## ggplot theme updates
source(here::here("theme", "tidy_grey.R"))

theme_set(theme_custom(base_family = "Montserrat"))
theme_update(rect = element_rect(fill = "grey10"),
             panel.border = element_rect(color = "grey30"),
             axis.ticks = element_line(color = "grey30"),
             axis.text = element_text(color = "grey50"),
             plot.title = element_text(size = 30, 
                                       family = "Montserrat ExtraBold",
                                       hjust = 0.5),
             plot.subtitle = element_markdown(size = 12, 
                                              family = "Bitter", 
                                              color = "grey50", 
                                              lineheight = 1.4,
                                              hjust = 0.5),
             plot.caption = element_text(size = 9, 
                                         family = "Bitter", 
                                         color = "grey50"))
```

```{r data}
df_schools <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-24/school_diversity.csv")
```

```{r prep-data}
df_school_index <- 
  df_schools %>% 
  group_by(ST) %>% 
  mutate_at(vars(AIAN:Multi), ~ replace_na(., 0)) %>% 
  mutate(
    total = AIAN + Asian + Black + Hispanic + White + Multi,
    prop_whites = median(White)
  ) %>%
  ungroup() %>% 
  mutate(prop_whites = White) %>% 
  dplyr::select(LEAID, ST, SCHOOL_YEAR, AIAN:Multi, total, prop_whites) %>% 
  gather(ethnicity, value, -c(LEAID, ST, SCHOOL_YEAR, total, prop_whites)) %>% 
  filter(value > 0) %>% 
  group_by(LEAID, ST, SCHOOL_YEAR, prop_whites) %>% 
  summarize(
    simpson = (1 - sum(value * (value - 1)) / (100*(100 - 1))),
    shannon = -sum((value / total) * log(value / total))
  ) %>% 
  ungroup()
```

## Main plot

```{r biscale-map}
## biscale map
df_schools_biscale <- 
  df_school_index %>% 
  filter(SCHOOL_YEAR == "2016-2017") %>% 
  group_by(ST) %>% 
  summarize(
    simpson = median(simpson),
    prop_whites = median(prop_whites)
  ) %>% 
  bi_class(x = simpson, y = prop_whites, style = "quantile", dim = 3)

map <- 
  fifty_states %>%
  as_tibble() %>%
  mutate(region = stringr::str_to_title(id)) %>% 
  left_join(state_ranks[, 1:2], by = c("region" = "name")) %>% 
  full_join(df_schools_biscale, by = c("state" = "ST")) %>% 
  ggplot() +
    geom_map(aes(map_id = id, fill = bi_class), 
             map = fifty_states,
             color = "grey20",
             size = 0.01) +  
    expand_limits(x = fifty_states$long, y = fifty_states$lat) +
    fifty_states_inset_boxes() +
    bi_scale_fill(pal = "Brown", dim = 3, guide = F) +
    coord_map() +
    scale_x_continuous(breaks = NULL) + 
    scale_y_continuous(breaks = NULL) +
    theme(panel.background = element_blank(),
          panel.border = element_blank()) +
    labs(x = NULL, y = NULL,
         title = "How diverse are schools in the US?", 
         subtitle = "<br>Bivariate map showing the combination of racial diversity measured as <b style='color:#C8B35A'>Simpson index</b>, a quantitative diversity measure,<br>and the <b style='color:#9972AF'>proportion of students with white ethnicity</b> during the <b>school year 2016–2017</b>.")

legend <- 
  bi_legend(pal = "Brown",
            dim = 3,
            xlab = "Diversity ",
            ylab = "% Whites ") +
  theme_custom() +
  theme(rect = element_rect(fill = "grey10"),
        panel.border = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_text(size = 10,
                                    color = "grey70"),
        axis.title.y = element_text(size = 10,
                                    color = "grey70"))

map_legend <- ggdraw() +
  draw_plot(map, 0, 0, 1, 1) +
  draw_plot(legend, 0.75, 0.1, 0.2, 0.2)
```

```{r beeswarm-diversity}
## beeswarm diversity
beeswarm_simpson <- 
  df_school_index %>% 
  filter(SCHOOL_YEAR == "2016-2017") %>% 
  group_by(ST) %>% 
  mutate(
    median = median(simpson),
    simpson_h = if_else(simpson >= median, simpson, NA_real_),
    simpson_l = if_else(simpson < median, simpson, NA_real_)
  ) %>% 
  ungroup() %>% 
  mutate(median_all = median(simpson)) %>% 
  group_by(ST, median_all) %>% 
  mutate(diff = unique(median) - unique(median_all)) %>% 
  ungroup() %>% 
  mutate(ST = fct_reorder(ST, -median)) %>% 
  ggplot(aes(ST, simpson,
             fill = diff)) + 
    ggbeeswarm::geom_beeswarm(aes(ST, simpson_l), 
                              priority = 'descending', 
                              cex = 0.32,
                              size = 1.2, 
                              stroke = 0.05,
                              color = "grey40", 
                              shape = 21) +
    ggbeeswarm::geom_beeswarm(aes(ST, simpson_h),
                              cex = 0.32,
                              size = 1.2,
                              stroke = 0.05,
                              color = "white", 
                              shape = 21) +
    geom_hline(aes(yintercept = median_all), 
               color = "grey50", 
               linetype = "dashed",
               size = 0.1) +
    geom_point(aes(ST, median),
               color = "grey10", 
               shape = 21, 
               size = 3,
               stroke = 0.6) +
    scale_fill_gradient2(low = "#E8E8E8", 
                         mid = "#E4D9AC",
                         high = "#C8B35A",
                         guide = F) +
    theme(axis.text.x = element_text(size = 9,
                                     face = "bold"),
          axis.text.y = element_text(size = 9, 
                                     family = "Roboto Mono")) +
    labs(x = NULL, y = NULL, title = NULL,
         subtitle = "<b style='color:#E4D9AC'>Simpson diversity index</b> for all schools grouped per state, ranked from states with <b style='color:#C8B35A'>high diversity</b> to those with <b style='color:#E8E8E8'>low diversity</b>.<br>Larger dots represent each state's median diversity with darker colored points laying below and lighter colored points laying above this value.<br>")
```

```{r beeswarm-whites}
## beeswarm whites
beeswarm_whites <- 
  df_school_index %>% 
  filter(SCHOOL_YEAR == "2016-2017") %>% 
  group_by(ST) %>% 
  mutate(
    median = median(prop_whites),
    whites_h = if_else(prop_whites >= median, prop_whites, NA_real_),
    whites_l = if_else(prop_whites < median, prop_whites, NA_real_)
  ) %>% 
  ungroup() %>% 
  mutate(median_all = median(prop_whites)) %>% 
  group_by(ST, median_all) %>% 
  mutate(diff = unique(median) - unique(median_all)) %>% 
  ungroup() %>% 
  mutate(ST = fct_reorder(ST, median)) %>% 
  ggplot(aes(ST, median,
             fill = diff)) + 
    ggbeeswarm::geom_beeswarm(aes(ST, whites_l), 
                              priority = 'descending', 
                              cex = 0.23,
                              size = 1.2,
                              stroke = 0.05,
                              color = "white", 
                              shape = 21) +
    ggbeeswarm::geom_beeswarm(aes(ST, whites_h),
                              cex = 0.23,
                              size = 1.2, 
                              stroke = 0.05,
                              color = "grey40", 
                              shape = 21) +
    geom_hline(aes(yintercept = median_all), 
               color = "grey50", 
               linetype = "dashed",
               size = 0.1) +
    geom_point(aes(ST, median),
               color = "grey10",
               shape = 21, 
               size = 3,
               stroke = 0.6) +
    scale_y_continuous(breaks = seq(0, 100, by = 20),
                       labels = glue::glue("{seq(0, 100, by = 20)}%")) +   
    scale_fill_gradient2(low = "#E8E8E8", 
                         mid = "#CBB8D7",
                         high = "#9972AF",
                         guide = F) +
    theme(axis.text.x = element_text(size = 9,
                                     face = "bold"),
          axis.text.y = element_text(size = 9,
                                     family = "Roboto Mono")) +
    labs(x = NULL, y = NULL,
         subtitle = "<br><b style='color:#CBB8D7'>Proportion of white students</b> for all schools grouped per state, ranked from states with <b style='color:#E8E8E8'>few white students</b> to those with <b style='color:#9972AF'>many white students</b>.<br>Larger dots represent each state's median proportion with lighter colored points laying below and darker colored points laying above this value.<br>",
         caption = "\n\nVisualization by Cédric Scherer  |  Data: NCES")
```

```{r full-panel, fig.width = 14, fig.height = 16.5}
## panel
map_legend / beeswarm_simpson / beeswarm_whites + plot_layout(heights = c(1, 0.25, 0.25))

ggsave(here::here("plots", "2019_39", "2019_39_SchoolDiversity_brpurp.pdf"), 
       width = 14, height = 17, device = cairo_pdf)
```

***
  
```{r}
sessionInfo()
```
