---
title: "TidyTuesday 2019/39 - School Diversity by NCES"
author: "Cedric Scherer"
date: "25th of September 2019"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep, message=FALSE, warning=FALSE}
## packages
library(tidyverse)
library(broom)
library(geojsonio)
library(rgdal)
library(rgeos)
library(patchwork)
library(showtext)

## ggplot theme updates
source(here::here("theme", "tidy_grey.R"))

theme_set(theme_custom(base_family = "Merriweather Sans"))

theme_update(rect = element_rect(fill = "grey10"),
             panel.border = element_blank(),
             axis.ticks = element_blank(),
             axis.text = element_blank(),
             axis.title = element_blank(),
             legend.position = c(0.48, 0.92),
             legend.title = element_text(size = 12, 
                                         color = "grey75",
                                         lineheight = 1.04),
             legend.text = element_text(family = "Roboto Mono", 
                                        color = "grey75", 
                                        size = 11),
             plot.title = element_text(size = 27,
                                       hjust = 0.5,
                                       margin = margin(t = 15, b = 40)),
             plot.caption = element_text(size = 12, 
                                         color = "grey45",
                                         hjust = 0.5,
                                         margin = margin(t = 30, b = 10)))
```

```{r data}
df_schools <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-09-24/school_diversity.csv")

df_states <- readr::read_csv(here::here("data", "50_us_states_all_data.csv"), col_names = F) %>% 
  dplyr::select(state = "X2", ISO2 = "X3") %>% 
  add_row(state = "District of Columbia", ISO2 = "DC")

map_hex <- geojson_read(here::here("data", "us_states_hexgrid.geojson.json"),  what = "sp")

map_hex@data <-
  map_hex@data %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))
```

```{r prep-data}
df_schools_index_wide <- 
  df_schools %>% 
  group_by(ST) %>% 
  mutate_at(vars(AIAN:Multi), ~ replace_na(., 0)) %>% 
  mutate(
    total = AIAN + Asian + Black + Hispanic + White + Multi,
    prop_whites = median(White)
  ) %>%
  ungroup() %>% 
  mutate(prop_whites = White) %>% 
  dplyr::select(LEAID, ST, SCHOOL_YEAR, AIAN:Multi, total) %>% 
  gather(ethnicity, value, -c(LEAID, ST, SCHOOL_YEAR, total)) %>% 
  filter(value > 0) %>% 
  group_by(LEAID, ST, SCHOOL_YEAR) %>% 
  summarize(simpson = (1 - sum(value * (value - 1)) / (100*(100 - 1)))) %>% 
  group_by(ST, SCHOOL_YEAR) %>% 
  summarize(simpson = mean(simpson, na.rm = T)) %>% 
  pivot_wider(names_from = SCHOOL_YEAR, values_from = simpson) %>% 
  mutate(change = `2016-2017` - `1994-1995`)

map_hex@data <-
  map_hex@data %>%
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))

## fortify
map_hex_fortified <- tidy(map_hex, region = "google_name")

## centroids for labels
centroids <- cbind.data.frame(data.frame(gCentroid(map_hex, byid = T), id = map_hex@data$iso3166_2))
 
## combine data
df_schools_hex <- 
  map_hex_fortified %>%
  left_join(df_states, by = c("id" = "state")) %>% 
  left_join(df_schools_index_wide, by = c("ISO2" = "ST"))
```

## Hex map

```{r hex-bin-maps}
map_hex_diversity <-
 ggplot(df_schools_hex) +
  geom_polygon(aes(long, lat, 
                   group = group, 
                   fill = `2016-2017`), 
               color = "grey85") +
  geom_text(data = centroids, 
            aes(x = x, y = y, label = id),
            family = "Montserrat",
            fontface = "bold") +
  coord_map() +
  rcartocolor::scale_fill_carto_c(palette = "SunsetDark", 
                                  name = "Simpson diversity index\nduring the 2016/17 school year ",
                                  limits = c(0, 0.65)) +
  guides(fill = guide_colorbar(barheight = unit(2.5, units = "mm"),  
                               barwidth = unit(90, units = "mm"),
                               direction = "horizontal",
                               ticks.colour = "grey10",
                               title.position = "top",
                               title.hjust = 0.5))

map_hex_change <-
 ggplot(df_schools_hex) +
  geom_polygon(aes(long, lat, 
                   group = group, 
                   fill = change), 
               color = "grey85") +
  geom_text(data = centroids, 
            aes(x = x, y = y, label = id),
            family = "Montserrat",
            fontface = "bold") +
  coord_map() +
  rcartocolor::scale_fill_carto_c(palette = "OrYel",
                                  name = "Change in the Simpson diversity index\ncompared to the 1994/95 school year",
                                  direction = -1) +
  guides(fill = guide_colorbar(barheight = unit(2.5, units = "mm"),  
                               barwidth = unit(90, units = "mm"),
                               direction = "horizontal",
                               ticks.colour = "grey10",
                               title.position = "top",
                               title.hjust = 0.5))

title <- ggplot(data.frame(x = 1:2, y = 1:10)) +
  labs(title = "United States schools became more racially diverse over the last decades",
       caption = "Visualization by Cédric Scherer  •  Data by National Center for Education Statistics (NCES)")

map_hex_diversity + title + map_hex_change + plot_layout(nrow = 1, widths = c(1, 0.01, 1))

ggsave(here::here("plots", "2019_39", "2019_39_SchoolDiversity_hex.pdf"), 
       width = 15, height = 6.5, device = cairo_pdf)
```

***
  
```{r}
sessionInfo()
```
