---
title: "TidyTuesday 2019/17 - Anime Data by MyAnimeList.net"
author: "Cedric Scherer"
date: "23rd of April 2019"
output:
  html_document:
    theme: paper
    highlight: kate
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r prep, message=FALSE}
## packages
library(tidyverse)
library(ggrepel)
library(patchwork)
library(ghibli)

## ggplot theme updates
source(here::here("R", "tidy_grey.R"))
```

```{r data}
df_ghibli <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-23/tidy_anime.csv") %>% 
  filter(studio == "Studio Ghibli", type == "Movie") %>% 
  dplyr::select(animeID, title_english, title_japanese, genre, score, scored_by, members)
```

```{r plot-genres}
img_a <- png::readPNG(here::here("img", "totoro.png")) 
a <- grid::rasterGrob(img_a, interpolate = T) 

ghibli_genres <- df_ghibli %>% 
  group_by(genre) %>% 
  count() %>% 
  filter(n > 5) %>% 
  ungroup() %>% 
  mutate(genre = fct_reorder(genre, n)) %>% 
  ggplot(aes(genre, n)) +
    geom_col(aes(fill = genre)) +
    coord_flip() +
    scale_y_continuous(limits = c(0, 20), expand = c(0.01, 0)) +
    scale_fill_ghibli_d("MononokeLight") +
    guides(fill = F) + 
    labs(x = "Most common genres", y = "Count") +
    annotation_custom(a, xmin = 0.4, xmax = 6.75, ymin = 12, ymax = 23) +
    theme(axis.text.x = element_text(family = "Roboto Mono"))
```

```{r plot-ratings}
img_b <- png::readPNG(here::here("img", "ghibli.png"))
b <- grid::rasterGrob(img_b, interpolate = T) 

set.seed(1)

df_ghibli_unique <-df_ghibli %>% 
  group_by(animeID) %>% 
  summarize_all(first) %>% 
  mutate(title = glue::glue("{title_japanese}\n({title_english})"))

ghibli_scores <- df_ghibli_unique %>% 
  ggplot(aes(score, scored_by)) +
    geom_point(aes(size = members), color = "#F4C59D", alpha = 0.6) +
    geom_text_repel(data = filter(df_ghibli_unique, scored_by > 120000), aes(label = title), size = 1.75, family = "Poppins", 
                    color = "#F4C59D", segment.size = 0.3, xlim = c(9.25, 10), box.padding = 0.5, force = 5) +
    scale_x_continuous(limits = c(5, 10)) +
    scale_y_continuous(labels = scales::comma, limits = c(0, 600000)) + 
    scale_size_continuous(name = "Times listed by MAL users:",
                          breaks = c(1000, 10000, 100000, 250000, 500000), 
                          labels = c("  1,000", " 10,000", "100,000", "250,000", "500,000")) +
    guides(size = guide_legend(override.aes = list(alpha = 1))) +
    labs(x = "Average MAL user score", y = "Number of ratings",
         caption = "\nVisualization by Cédric Scherer  |  Picture credit: Studio Ghibli, Inc & MangoKingoroo") +
    annotation_custom(b, xmin = 5, xmax = 8, ymin = 400000, ymax = 600000) +
    theme(axis.text = element_text(family = "Roboto Mono"),
          legend.position = c(0.32, 0.4),
          legend.background = element_rect(fill = "transparent"),
          legend.title = element_text(size = 9),
          legend.text = element_text(family = "Roboto Mono", size = 8))
```

```{r title}
## left-alligned title
title <- ggplot(data.frame(x = 1:2, y = 1:10)) +
  labs(x = NULL, y = NULL,
       title = "Studio Ghibli movies listed on MyAnimeList.net (MAL)",
       subtitle = "") +
  theme(line = element_blank(),
        plot.background = element_rect(fill = "transparent", color = "transparent"),
        plot.subtitle = element_text(size = 7),
        panel.background = element_rect(fill = "transparent"),
        panel.border = element_rect(color = "transparent"),
        axis.text = element_blank())
```

```{r fullpanel, fig.width = 14, fig.heigth = 5}
## full panel
title + ghibli_genres + ghibli_scores + plot_layout(width = c(0, 1, 1))

ggsave(here::here("plots", "2019_17", "2019_17_animes.png"), 
       width = 14, height = 5.1, dpi = 300)
```

***

```{r session}
sessionInfo()
```
