---
title: "TidyTuesday 2020/18 - Broadway Musicals by Playbill"
author: "Cedric Scherer"
date: "28th of April 2020"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep, message=FALSE, warning=FALSE}
## packages
library(tidyverse)
library(ggforce)
library(ggtext)
library(extrafont)
library(showtext)

loadfonts()
font_add_google("Staatliches", "Staatliches")

## ggplot theme
theme_set(theme_minimal(base_family = "Britannic Bold"))

theme_update(axis.text = element_text(size = 14, color = "grey45"),
             legend.title = element_text(size = 16, color = "grey65", face = "bold"),
             legend.text = element_text(family = "Staatliches", size = 11, color = "grey45", face = "plain"),
             panel.grid = element_blank(),
             plot.background = element_rect(fill = "grey12", color = "grey12"),
             plot.margin = margin(30, 80, 10, 50),
             plot.title = element_markdown(size = 29, color = "grey97", 
                                           face = "plain", lineheight = 1.15),
             plot.title.position = "plot",
             plot.subtitle = element_text(color = "grey45", size = 15, face = "plain",
                                          margin = margin(t = 25, b = 15)),
             plot.caption = element_text(color = "grey35", size = 12, face = "bold",
                                          margin = margin(40, -300, 15, 0)),
             plot.caption.position = "plot")
```

```{r data}
df_grosses <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-28/grosses.csv', guess_max = 40000)

pre_1985_starts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-28/pre-1985-starts.csv')
```


```{r data-prep}
df_gross_show <- 
  df_grosses %>% 
  mutate(year = lubridate::year(week_ending)) %>% 
  filter(avg_ticket_price > 0) %>% 
  group_by(show) %>% 
  summarize(
    year = min(year),
    weekly_gross_overall = sum(weekly_gross_overall, na.rm = T),
    avg_ticket_price = mean(avg_ticket_price, na.rm = T),
    top_ticket_price = mean(top_ticket_price, na.rm = T),
    seats_sold = sum(seats_sold, na.rm = T)
  ) %>% 
  mutate(gross_per_seat = weekly_gross_overall / seats_sold) %>% 
  ungroup() %>% 
  left_join(pre_1985_starts) %>%
  filter(show != "Les Miserables") %>% 
  mutate(
    show = case_when(
      show == "Hamilton" ~ "A high ranked musical\nI never heard of.",
      show == "Springsteen On Broadway" ~ "I thought this guy plays concerts?",
      show == "The Lion King" ~ "Of course I've\nseen the movie!\nBut the musical?",
      show == "Chicago" ~ "Another high-ranked\none I had no idea of.",
      show == "Wicked" ~ "At least I know\nthe classic novel.",
      show == "The Phantom of the Opera" ~ "I love the music!",
      show == "Cats" ~ "Wouldnt even go\nthere for free...",
      show == "Marc Salem's Mind Games on Broadway" ~ "I even wrapped already\nall the long brodway\nshow names using the\ncool str_wrap() function\nbefore realizing it doesn't\nmake any sense at all.",
      show == "A Mom's Life" ~ "A very interesting outlier!\n(I thought.)",
      TRUE ~ " "
    ),
    year = if_else(!is.na(start_date), lubridate::year(start_date), year)
  )
```


```{r nonsense-plot, fig.width = 18.1, fig.height = 14}
df_gross_show %>% 
  ggplot(aes(gross_per_seat, avg_ticket_price)) +
    geom_point(aes(size = seats_sold),
               shape = 21,
               fill = "grey10",
               color = "transparent") +
    geom_point(data = df_gross_show %>% 
                 filter(avg_ticket_price >= 220 | gross_per_seat >= 30000 | seats_sold >= 8.5*10^6),
               aes(fill = year, 
                   size = seats_sold),
               shape = 21,
               alpha = .2,
               color = "transparent") +
    geom_point(aes(fill = year, 
                   size = seats_sold),
               shape = 21,
               color = "transparent",
               alpha = .2) +
    geom_point(aes(color = year, 
                   color = after_scale(colorspace::darken(color, .05)),
                   size = seats_sold),
               shape = 21,
               fill = "transparent",
               stroke = .5) +
    geom_point(data = df_gross_show %>% 
                 filter(avg_ticket_price >= 220 | gross_per_seat >= 30000 | seats_sold >= 8.5*10^6),
               aes(color = year, 
                   color = after_scale(colorspace::lighten(color, .05)),
                   size = seats_sold),
               shape = 21,
               fill = "transparent",
               stroke = 1.1) +
    geom_mark_ellipse(data = df_gross_show %>% 
                        filter(avg_ticket_price >= 220 | gross_per_seat >= 30000 | seats_sold >= 8.5*10^6),
                      aes(group = show, 
                          label = show),
                      color = "transparent",
                      label.family = "Staatliches",
                      label.fontsize = 16,
                      label.fill = "#ffffff80",
                      label.buffer = unit(5, "mm"),
                      con.colour = "grey90",
                      con.size = .6,
                      con.cap = unit(0, "mm"),
                      expand = unit(5, "mm"),
                      con.type = "elbow") +
    geom_segment(data = tibble(x = c(350, 300), xend = c(80000, 300), 
                               y = c(6, 7), yend = c(6, 600)),
                 aes(x, y, xend = xend, yend = yend),
                 color = "grey45",
                 size = .6,
                 arrow = arrow(length = unit(.1, "inches"))) +
    geom_text(aes(85000, 6, 
                  label = "A non-sense ratio"),
              family = "Britannic Bold",
              color = "grey45",
              fontface = "plain",
              size = 5.5,
              hjust = 0) +
    geom_text(aes(300, 650, 
                  label = "Ticket price\n(confusing log-scale)"),
              family = "Britannic Bold",
              color = "grey45",
              fontface = "plain",
              lineheight = .9,
              size = 5.5,
              vjust = 0) +
    coord_cartesian(clip = "off") +
    scale_x_log10(expand = c(.001, .001),
                  limits = c(NA, 160000),
                  breaks = c(500, 5000, 50000),
                  labels = c("Non-sense\nvalue", "Non-sense\nvalue", "Non-sense\nvalue")) +
    scale_y_log10(expand = c(.001, .001),
                  limits = c(NA, 1000),
                  breaks = c(10, 30, 100, 300),
                  labels = c("$", "$$", "$$$$", "   $$$$$$$$")) +
    rcartocolor::scale_color_carto_c(palette = "Sunset", 
                                     guide = F) +
    rcartocolor::scale_fill_carto_c(palette = "Sunset", 
                                  name = "Year of first broadway show",
                                  breaks = c(1975, 1980, 1990, 2000, 2010, 2020)) +
    scale_radius(range = c(2, 12),
                 name = "Seats sold",
                 breaks = c(10000, 100000, 1000000, 5000000, 10000000),
                 labels = c("10,000  ", "100,000  ", "1 million  ", "5 million  ", "10 millions")) +
    guides(fill = guide_colorbar(direction = "horizontal",
                                 title.position = "top",
                                 title.hjust = .5,
                                 barwidth = unit(24.5, "lines"),
                                 barheight = unit(.4, "lines")),
           size = guide_legend(direction = "horizontal",
                               title.position = "top",
                               title.hjust = .5,
                               override.aes = list(fill = "#FAA476", 
                                                   color = "#FAA476"))) +
    labs(x = NULL, y = NULL,
         title = "<b style='font-size:36pt;'>This could be an insightful plot... if only I knew something about broadways.</b><br><span style='color:#b0b0b0'>a.k.a. a friendly reminder to myself that I should </span><span style='color:#f3e79b;'>read</span> <span style='color:#fab27f;'>the</span> <span style='color:#eb7f86;'>f**cking</span> <span style='color:#b95e9a;'>manual",
         subtitle = "This week's #TidyTuesday challenge is on Broadway Musicals—a topic I know nothing about—and I decided to ignore the glossary and jump right in.\nTurns out I've spent 3 hours to explore the data and polish the plot just to find out it makes no freaking sense at all.",
         caption = "Visualization by Cédric Scherer  •  Data by Playbill") +
    theme(legend.position = c(.83, .83),
          legend.box = "vertical")

ggsave(here::here("plots", "2020_18", "2020_18_BroadwayMusicals.pdf"),
       width = 18.1, height = 14,  device = cairo_pdf)

pdftools::pdf_convert(here::here("plots", "2020_18", "2020_18_BroadwayMusicals.pdf"),
                      format = "png", dpi = 250)
```

***

```{r session-info}
sessionInfo()
```

