---
title: "TidyTuesday 2020/03 - Passwords by Knowledge Is Beautiful"
author: "Cedric Scherer"
date: "14th of January 2020"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep, message=FALSE, warning=FALSE}
## packages
library(tidyverse)
library(ggtext)
library(extrafont)
library(patchwork)
```

```{r data}
df_pw <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv') %>% 
  filter(!is.na(password))
```

```{r data-prep}
df_pw_time <-
  df_pw %>% 
  mutate(
    #value = offline_crack_sec,
    time = case_when(
      time_unit == "seconds" ~ value,
      time_unit == "minutes" ~ value * 60,
      time_unit == "hours" ~ value * 60 * 60,
      time_unit == "days" ~ value * 60 * 24,
      time_unit == "weeks" ~ value * 60 * 24 * 7,
      time_unit == "months" ~ value * 60 * 24 * 30,
      time_unit == "years" ~ value * 60 * 24 * 365,
      TRUE ~ NA_real_
    )
  ) 
```

```{r main-plot}
plus <- 1000

df_pw_plot <-
  df_pw_time %>% 
  mutate(time = time + plus) %>% 
  add_row(rank = 501, time = 1)

labels <-
  df_pw_plot %>% 
  filter(value > 90) %>% 
  mutate(label = glue::glue("<b>{password}</b><br><span style='font-size:18pt'>Rank: {rank}</span>")) %>% 
  add_column(
    x = c(33, 332, 401, 492),
    y = c(75000000, 90000000, 45000000, 48498112)
  )

main <- 
  df_pw_plot %>% 
  mutate(category = factor(category)) %>% 
  ggplot(aes(rank, time, color = category)) +
    geom_segment(aes(x = rank, xend = rank, y = 0, yend = time), 
                 size = 1.2) +
    geom_rect(aes(xmin = 1, xmax = 501, ymin = 0, ymax = plus), 
              fill = "grey97", color = "grey97") + 
    geom_hline(aes(yintercept = (1 * 24 * 60 + plus)), color = "grey88") +
    geom_hline(aes(yintercept = (7 * 24 * 60 + plus)), color = "grey85") +
    geom_hline(aes(yintercept = (30 * 24 * 60 + plus)), color = "grey82") +
    geom_hline(aes(yintercept = (365 * 24 * 60 + plus)), color = "grey79") +
    geom_point(aes(size = time)) +
    geom_richtext(data = labels,
                  aes(x = x, y = y,
                      label = label,
                      color = category),
                  lineheight = 0.8,
                  size = 8,
                  family = "Roboto Mono",
                  label.color = NA) +
    geom_text(x = 500, y = 1.2,
                  label = "********\nCracking\nYour Favorite\nPassword",
                  family = "Roboto Mono Medium",
                  size = 20,
                  lineheight = 0.87,
                  color = "grey60") +
    geom_text(x = 250, y = 0.25,
                  label = "********",
                  family = "Roboto Mono Medium",
                  size = 20,
                  lineheight = 0.87,
                  color = "grey60") +
    geom_text(x = 250, y = 1.1,
                  label = "Time it takes to crack the 500 most\ncommon passwords by online guessing.\nSorted by rank and colored by category.",
                  family = "Roboto Mono",
                  size = 7,
                  lineheight = 0.87,
                  color = "grey73") +
    geom_text(x = 250, y = 1.95,
                  label = "Time is displayed on a logarithmic scale\nwith the rings representing one day,\none week, one month, and one year\n(from inner to outer ring).",
                  family = "Roboto Mono",
                  size = 6,
                  lineheight = 0.87,
                  color = "grey73") +
    coord_polar() + 
    scale_y_log10(expand = c(0, 0)) +
    rcartocolor::scale_color_carto_d(palette = "Prism", 
                                     guide = F) +
    scale_size(range = c(1, 8), 
               limits = c(plus, max(df_pw_plot$time)), 
               guide = F) + 
    theme_void() +
    theme(plot.margin = margin(-50, -180, -70, -180, "lines"))
```

```{r facet}
facet <- 
  df_pw_plot %>% 
  add_row(rank = 501, time = 1, category = unique(df_pw_plot$category)) %>% 
  mutate(
    cat_label = case_when(
      category == "cool-macho" ~ "cool-\nmacho",
      category == "nerdy-pop" ~ "nerdy-\npop",
      category == "password-related" ~ "password-\nrelated",
      category == "rebellious-rude" ~ "rebel-\nlious-\nrude",
      category == "simple-alphanumeric" ~ "simple-\nalpha-\nnumeric",
      TRUE ~ category
    )
  ) %>% 
  filter(!is.na(category)) %>% 
  mutate(category = factor(category), cat_label = factor(cat_label)) %>% 
  ggplot(aes(rank, time, color = category)) +
    geom_segment(aes(x = rank, xend = rank, y = 0, yend = time), 
                 size = 0.6) +
    geom_rect(aes(xmin = 1, xmax = 501, ymin = 0, ymax = plus), 
              fill = "grey97", color = "grey97") + 
    geom_hline(aes(yintercept = (1 * 24 * 60 + plus)), color = "grey82", size = 0.2) +
    geom_hline(aes(yintercept = (7 * 24 * 60 + plus)), color = "grey79", size = 0.2) +
    geom_hline(aes(yintercept = (30 * 24 * 60 + plus)), color = "grey76", size = 0.2) +
    geom_hline(aes(yintercept = (365 * 24 * 60 + plus)), color = "grey73", size = 0.2) +
    geom_point(aes(size = time)) +
    geom_text(aes(label = cat_label, color = category),
              x = 500, y = 0,
              family = "Roboto Mono Medium",
              size = 8,
              lineheight = 0.87) +
    facet_wrap(~ category, nrow = 2) +
    coord_polar() + 
    scale_y_log10(expand = c(0, 0)) + 
    rcartocolor::scale_color_carto_d(palette = "Prism", 
                                     guide = F) +
    scale_size(range = c(0.5, 7), 
               limits = c(plus, max(df_pw_plot$time)), 
               guide = F) + 
    theme_void() +
    theme(strip.text = element_blank(), 
          panel.spacing = unit(-8, "lines"),
          plot.margin = margin(-40, 50, 10, 50),
          plot.background = element_rect(fill = NA, color = NA),
          panel.background = element_rect(fill = NA, color = NA),
          plot.caption = element_text(family = "Roboto Mono Medium", 
                                      size = 20, 
                                      color = "grey60", 
                                      hjust = 0.5, 
                                      margin = margin(-50, 10, 30, 10))) +
    labs(caption = "Visualization by Cédric Scherer ∙ Data by Knowledge is Beautiful")
```

```{r full-panel, fig.width = 30, fig.height = 35}
(panel <- (main + facet) + plot_layout(ncol = 1, heights = c(1 , 0.28)))

ggsave(here::here("plots", "2020_03", "2020_03_Password.pdf"), plot = panel,
       width = 30, height = 35, device = cairo_pdf, limitsize = F)
```

***
  
```{r}
sessionInfo()
```
