---
title: "TidyTuesday 2020/12 - The Office Ratings by IMDb & data.world"
author: "Cedric Scherer"
date: "24th of March 2020"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep, message=FALSE, warning=FALSE}
## packages
library(tidyverse)
library(cowplot)
library(showtext)

font_add_google("Roboto Mono", "Roboto Mono")
font_add_google("Open Sans", "Open Sans")
font_add_google("Special Elite", "Special Elite")

## ggplot theme
theme_set(theme_minimal(base_family = "Roboto Mono"))

theme_update(plot.background = element_rect(fill = "#fafaf5", color = "#fafaf5"),
             panel.background = element_rect(fill = NA, color = NA),
             panel.border = element_rect(fill = NA, color = NA),
             panel.grid.major.x = element_blank(),
             panel.grid.minor = element_blank(),
             axis.text.x = element_blank(),
             axis.text.y = element_text(size = 10),
             axis.ticks = element_blank(),
             axis.title.y = element_text(size = 13, 
                                         margin = margin(r = 10)),
             legend.title = element_text(size = 9),
             plot.caption = element_text(family = "Special Elite",
                                         size = 10,
                                         color = "grey70",
                                         face = "bold",
                                         hjust = .5,
                                         margin = margin(5, 0, 20, 0)),
             plot.margin = margin(10, 25, 10, 25))
```

```{r data}
df_office <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-17/office_ratings.csv')
```


```{r data-prep}
df_office_avg <-
  df_office %>% 
  arrange(season, episode) %>% 
  mutate(episode_id = row_number()) %>% 
  group_by(season) %>% 
  mutate(
    avg = mean(imdb_rating),
    episode_mod = episode_id + (9 * season),
    mid = mean(episode_mod)
  ) %>% 
  ungroup() %>% 
  mutate(season = factor(season))

df_lines <-
  df_office_avg %>% 
  group_by(season) %>% 
  summarize(
    start_x = min(episode_mod) - 5,
    end_x = max(episode_mod) + 5,
    y = unique(avg)
  ) %>% 
  pivot_longer(
    cols = c(start_x, end_x),
    names_to = "type",
    values_to = "x"
  ) %>% 
  mutate(
    x_group = if_else(type == "start_x", x + .1, x - .1),
    x_group = if_else(type == "start_x" & x == min(x), x_group - .1, x_group),
    x_group = if_else(type == "end_x" & x == max(x), x_group + .1, x_group)
  )
```


```{r plot, fig.width = 15, fig.height = 9}
p <- df_office_avg %>% 
  ggplot(aes(episode_mod, imdb_rating)) +
    geom_hline(data = tibble(y = 7:10),
               aes(yintercept = y),
               color = "grey82",
               size = .5) +
    geom_segment(aes(xend = episode_mod,
                     yend = avg, 
                     color = season, 
                     color = after_scale(colorspace::lighten(color, .2)))) +
    geom_line(data = df_lines,
              aes(x, y),
              color = "grey40") +
    geom_line(data = df_lines,
              aes(x_group, y, 
                  color = season, 
                  color = after_scale(colorspace::darken(color, .2))),
              size = 2.5) +
    geom_point(aes(size = total_votes,
                   color = season)) +
    geom_label(aes(mid, 10.12,
                   label = glue::glue(" Season {season} "),
                   color = season, 
                   color = after_scale(colorspace::darken(color, .2))),
               fill = NA,
               family = "Special Elite",
               fontface = "bold",
               label.padding = unit(.2, "lines"),
               label.r = unit(.25, "lines"),
               label.size = .5) +
    scale_x_continuous(expand = c(.015, .015)) +
    scale_y_continuous(expand = c(.03, .03),
                       limits = c(6.5, 10.2),
                       breaks = seq(6.5, 10, by = .5),
                       sec.axis = dup_axis(name = NULL)) +
    scale_color_manual(values = c("#486090", "#D7BFA6", "#6078A8", "#9CCCCC", 
                                  "#7890A8", "#C7B0C1", "#B5C9C9", "#90A8C0", "#A8A890"),
                       guide = F) +
    scale_size_binned(name = "Votes per Episode",
                      range = c(.3, 3)) +
    labs(x = NULL, y = "IMDb Rating",
        caption = "Visualization by Cédric Scherer  •  Data by IMDb via data.world  •  Fanart Logo by ArieS") +
    guides(size = guide_bins(show.limits = T,
                             direction = "horizontal",
                             title.position = "top",
                             title.hjust = .5)) +
    theme(legend.position = c(.5, .085), 
          legend.key.width = unit(2, "lines"))

logo <- png::readPNG(here::here("img", "the-office.png"))

ggdraw(p) +
  draw_image(logo, x = -.35, y = -.34, scale = .12)

ggsave(here::here("plots", "2020_12", "2020_12_TheOffice.pdf"), 
       width = 15, height = 9, device = cairo_pdf) 
```


***

```{r session-info}
sessionInfo()
```

