---
title: "TidyTuesday 2020/02 - Australian Fires by Bureau of Meteorology"
author: "Cedric Scherer"
date: "6th of January 2020"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep, message=FALSE, warning=FALSE}
## packages
library(tidyverse)
library(sf)
library(ggtext)
library(showtext)

## ggplot theme updates
font_add_google("Oswald", "Oswald")
```

## European Comparison Burn Land & Plume of Smoke

```{r fires-europe, fig.width = 14, fig.height = 11.9}
sf_europe <- st_as_sf(rworldmap::getMap(resolution = "high")) %>% 
  st_transform(crs = "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") %>% 
  filter(REGION == "Europe") %>% 
  st_crop(xmin = -3500000, xmax = 2300000, ymin = 4100000, ymax = 9000000) %>% 
  mutate(
    area = st_area(geometry),
    centroid = st_centroid(geometry)
  ) %>% 
  dplyr::select(SOVEREIGNT, GLOCAF, area, centroid)

smoke_area <- 
  sf_europe %>% 
  filter(GLOCAF == "Europe") %>% 
  arrange(-area) %>% 
  mutate(
    area = as.numeric(area) / 1000000, 
    sum = cumsum(area)
  ) %>% 
  slice(1:9)
  
# labels <-
#   sf_europe %>% 
#   filter(SOVEREIGNT %in% smoke_area$SOVEREIGNT | SOVEREIGNT == "Latvia") %>% 
#   mutate(
#     lon = st_coordinates(.$centroid)[,1],
#     lat = st_coordinates(.$centroid)[,2]
#   ) %>% 
#   st_set_geometry(NULL) %>% 
#   slice(c(-1, -7, -8)) %>% 
#   st_as_sf(coords = c("lat", "lon"))

## Burned area: 63,000 sq km ~ Lativa (2020/01/06)
## Area covered with smoke: 5.5 million sq km ~ Denmark + France + Spain + Sweden + Norway + Germany + Finland + Poland + Italy 

map <- ggplot(sf_europe) +
  geom_sf(color = "grey85",
          fill = "grey90",
          lwd = 0.1) +
  geom_sf(data = filter(sf_europe, SOVEREIGNT == "Latvia"), 
          color = "#9d1e1e",
          fill = "#c82626",
          lwd = 0.2) +
  geom_sf(data = filter(sf_europe, SOVEREIGNT %in% smoke_area$SOVEREIGNT), 
          color = "#c49c67",
          fill = "#d9c09e",
          lwd = 0.2) +
  #geom_sf_text(data = labels,
  #             aes(label = SOVEREIGNT),
  #             family = "Oswald", size = 2) +
  geom_richtext(aes(x = -2050000, y = 5850000, 
                    label = "<span style='color:#9d1e1e'>Burnt Land</span> and <span style='color:#c49c67'>Plume of Smoke</span> Caused<br>by the Australian Bushfires in 2019/20<br>in Comparison to European Countries"),
                family = "Oswald",
                color = "grey20",
                size = 7,
                fontface = "bold",
                label.color = NA) +
  geom_richtext(aes(x = -2050000, y = 5400000, 
                    label = "An area of bush, forest and parks larger than <span style='color:#9d1e1e'>Latvia</span> have been burned<br>during a series of massive bushfires across Australia. Thick smoke<br>covering about the area of <span style='color:#c49c67'>Denmark (incl. Greenland and the Faroe<br>Islands), France, Spain, Sweden, Norway, Germany, Finland, Poland & Italy</span><br>has started drifting over the Pacific Ocean towards New Zealand."),
                family = "Oswald",
                color = "grey50",
                size = 4.7,
                label.color = NA) +
  geom_richtext(aes(x = -2050000, y = 5100000, 
                    label = "Status: 6th of January 2020"),
                family = "Oswald",
                color = "grey50",
                size = 3.7,
                label.color = NA) +
  geom_richtext(aes(x = -2050000, y = 4250000, 
                    label = "Visualization by Cédric Scherer  ∙  Data by NASA FIRMS & The Independent"),
                family = "Oswald",
                color = "grey70",
                size = 4.2,
                fontface = "bold",
                label.color = NA) +
  scale_x_continuous(expand = c(0, 0),
                     limits = c(-3300000, NA)) +
  scale_y_continuous(expand = c(0.02, 0.02)) +
  theme_void() + 
  theme(plot.margin = margin(0, 0, 0, 0))

ggsave(here::here("plots", "2020_02", "2020_02_AustralianFires.pdf"), 
       plot = map, width = 14, height = 11.9, device = cairo_pdf)
```

## Global Comparison Burnt Land

```{r fires-global, fig.width = 14, fig.height = 8.4}
sf_earth_burnt <- st_as_sf(rworldmap::getMap(resolution = "high")) %>% 
  st_transform(crs = "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs") %>% 
  mutate(
    area = st_area(geometry),
    centroid = st_centroid(geometry)
  ) %>% 
  dplyr::select(SOVEREIGNT, area, centroid) %>% 
  group_by(SOVEREIGNT) %>% 
  mutate(
    area = sum(as.numeric(area) * 0.000001),
    prop_burnt = 106966 / area,  ## burnt area: 41,300 sq miles (2020/01/08)
    cat_burnt = case_when(
      prop_burnt < 0.25 ~ "low [0-25%)",
      prop_burnt >= 0.25 & prop_burnt < 0.5 ~ "moderate-low [25-50%)",
      prop_burnt >= 0.5 & prop_burnt < 0.75 ~ "moderate-high [50-75%)",
      prop_burnt >= 0.75 & prop_burnt < 1 ~ "high [75-100%)",
      prop_burnt >= 1 ~ "all (\u2265 100%)"
    ),
    cat_burnt = factor(cat_burnt, 
                       levels = c("low [0-25%)", 
                                  "moderate-low [25-50%)", 
                                  "moderate-high [50-75%)", 
                                  "high [75-100%)", 
                                  "all (\u2265 100%)"))
  )

legend_title <- "How much of your country's area would have been burnt if the Australian bushfires had raged there?"

map_global <-
  sf_earth_burnt %>% 
  ggplot() +
    geom_sf(aes(color = cat_burnt, fill = cat_burnt), lwd = 0.2) +
    geom_richtext(aes(x = 8800000, y = -5800000, 
                      label = "As of 8<sup>th</sup> of January 2020,<br>the bushfires have burnt<br>41,300 mi<sup>2</sup> (106,966 km<sup>2</sup>),<br>1.4% of Australia's area."), 
                  family = "Oswald",
                  size = 3.7,
                  color = "grey55",
                  label.padding = unit(c(0.5, 0.5, 0.5, 0.5), "lines")) +
    scale_x_continuous(expand = c(0.02, 0.02)) +
    scale_y_continuous(limits = c(NA, 10500000)) +
    scale_fill_manual(values = c("#f5f5f5", "#efe3dc", "#e7bb9d", "#d2726a", "#ba0101"),
                      name = legend_title) +
    scale_color_manual(values = c("#dcdcdc", "#dfc7b9", "#dd9f74", "#c64d43", "#870101"),
                      name = legend_title) +
    guides(fill = guide_legend(title.position = "top", 
                               title.hjust = 0.5, nrow = 1,
                               label.position = "bottom")) +
    labs(caption = "Visualization by Cédric Scherer  ∙  Data by NASA FIRMS & The Guardian") +
    theme_void() +
    theme(plot.caption = element_text(family = "Oswald", 
                                      size = 10, 
                                      color = "grey70",
                                      face = "bold",
                                      hjust = 0.5,
                                      margin = margin(t = -15, b = 10)),
          panel.grid.major = element_line(color = "grey88", 
                                          size = 0.15),
          legend.position = c(0.5, 0.95),
          legend.key.height = unit(0.5, "lines"), 
          legend.key.width = unit(8.2, "lines"),
          legend.text = element_text(family = "Oswald", 
                                     color = "grey40", 
                                     size = 10),
          legend.title = element_text(family = "Oswald", 
                                      face = "bold", 
                                      color = "grey20", 
                                      size = 15))

ggsave(here::here("plots", "2020_02", "2020_02_AustralianFires_global.pdf"),
       plot = map_global, width = 14, height = 8.3, device = cairo_pdf)
```


<details><summary>Session Info</summary>

```{r sessionInfo, echo = F}
Sys.time()
git2r::repository()
sessionInfo()
```

</details>