---
title: "TidyTuesday 2020/08 - Food's Carbon Footprint by FAO & nu3"
author: "Cedric Scherer"
date: "7th of March 2020"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r prep, message=FALSE, warning=FALSE}
## packages
library(tidyverse)
library(rcartocolor)
library(ggtext)
library(cowplot)
library(patchwork)
library(showtext)

font_add_google("Fira Sans", "Fira Sans")
font_add_google("Playfair Display", "Playfair Display")

## ggplot theme
theme_set(theme_minimal(base_family = "Fira Sans"))

theme_update(plot.background = element_rect(fill = "transparent",
                                            color = "transparent"),
             panel.background = element_rect(fill = NA, color = NA),
             panel.grid = element_blank(),
             axis.ticks = element_blank(),
             axis.text = element_blank(),
             axis.title = element_blank(),
             plot.title = element_markdown(family = "Playfair Display",
                                           size = 90,
                                           color = "grey10",
                                           face = "bold",
                                           hjust = .5,
                                           margin = margin(80, 0, 20, 0)),
             plot.subtitle = element_markdown(size = 40,
                                              color = "grey30",
                                              face = "plain",
                                              hjust = .5,
                                              lineheight = 1.2,
                                              margin = margin(20, 0, -15, 0)),
             plot.caption = element_text(family = "Playfair Display",
                                         size = 30,
                                         color = "grey70",
                                         face = "bold",
                                         hjust = .5,
                                         margin = margin(0, 0, 30, 0)),
             plot.title.position = "plot",
             plot.caption.position = "plot",
             plot.margin = margin(10, 0, 10, 0))
```

```{r data}
df_food <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv')

countries <- readr::read_csv(here::here("data", "2020_08", "countryContinent.csv")) %>% 
  mutate(country = str_replace(country, "\\s\\(.*", "")) %>%
  mutate(country = str_replace(country, "\\,.*", "")) %>%
  mutate(
    country = case_when(
      country == "United Kingdom of Great Britain and Northern Ireland" ~ "United Kingdom",
      country == "United States of America" ~ "USA",
      country == "Russian Federation" ~ "Russia",
      country == "Viet Nam" ~ "Vietnam",
      code_3 == "KOR" ~ "South Korea",
      code_3 == "	PRK" ~ "North Korea",
      TRUE ~ country
    ),
    continent = case_when(
      sub_region %in% c("Northern America", "Central America", "Caribbean") ~ "North\nAmerica",
      sub_region == "South America" ~ "South\nAmerica",
      TRUE ~ continent
    )
  )

df_food_cont <-
  df_food %>%
  mutate(country = case_when(
    country == "Hong Kong SAR. China" ~ "Hong Kong",
    country == "Taiwan. ROC" ~ "Taiwan",
    TRUE ~ country
  )) %>%
  left_join(countries) %>%
  mutate(
    total_consumption = sum(consumption, na.rm = T),
    total_emmission = sum(co2_emmission, na.rm = T),
  ) %>%
  group_by(continent) %>%
  mutate(
    cont_consumption = sum(consumption, na.rm = T) / total_consumption,
    cont_emmission = sum(co2_emmission, na.rm = T) / total_emmission
  ) %>%
  group_by(continent, country, cont_consumption, cont_emmission, total_consumption, total_emmission) %>%
  summarize(
    count_consumption = sum(consumption, na.rm = T) / unique(total_consumption),
    count_emmission = sum(co2_emmission, na.rm = T) / unique(total_emmission)
  ) %>%
  ungroup()
```


## Food Consumption

```{r plot-consumption}
df_consumption <-
  df_food_cont %>%
  arrange(cont_consumption, count_consumption) %>%
  mutate(
    pos = cumsum(count_consumption),
    pos = if_else(!is.na(lag(pos)), pos - ((pos - lag(pos)) / 2), pos / 2),
    angle = 90 - 360 * (pos - 0.5),
    hjust = if_else(angle > 90, 0, 1),
    angle = ifelse(angle > 90, angle + 180, angle),
    label_big = if_else(
      country %in% (top_frac(df_food_cont, n = .5, wt = count_consumption) %>% pull(country)),
      country, NA_character_
    ),
    label_small = if_else(
      country %in% (top_frac(df_food_cont, n = .5, wt = -count_consumption) %>% pull(country)),
      country, NA_character_
    )
  ) %>%
  mutate(continent = fct_reorder(factor(continent), -cont_consumption)) %>%
  mutate(country = fct_reorder2(factor(country), as.numeric(continent), count_consumption, .desc = F)) %>%
  group_by(continent) %>%
  arrange(count_consumption) %>%
  mutate(
    alpha = count_consumption / max(count_consumption),
    pos_cont = min(pos) + (max(pos) - min(pos)) / 2,
    angle_cont = 90 - 360 * (pos_cont - 0.5),# / n(),
    hjust_cont = if_else(angle_cont > 90, 0, 1),
    angle_cont = ifelse(angle_cont > 90, angle_cont + 180, angle_cont)
  )

plot_c <-
  df_consumption %>%
  ggplot(aes(1, count_consumption)) +
    geom_col(
      aes(
        fill = continent,
        alpha = alpha,
        #color = after_scale(colorspace::darken(fill, .2)),
        fill = after_scale(colorspace::lighten(fill, .3))
      ),
      color = "white",
      size = .5
    ) +
    geom_col(
      aes(fill = continent,
          color = continent),
      width = .4,
      size = .3
    ) +
    geom_rect(
      xmin = -Inf, xmax = .8,
      ymin = -Inf, ymax = Inf,
      fill = "white"
    ) +
    geom_text(aes(1.475, pos,
                  label = label_big,
                  color = continent,
                  color = after_scale(colorspace::darken(color, .3)),
                  alpha = sqrt(alpha),
                  angle = angle,
                  hjust = hjust,
                  size = count_consumption^2),
              family = "Fira Sans",
              fontface = "bold") +
    geom_text(aes(1.475, pos,
                  label = label_small,
                  color = continent,
                  color = after_scale(colorspace::darken(color, .3)),
                  alpha = sqrt(alpha),
                  angle = angle,
                  hjust = hjust,
                  size = count_consumption^2),
              family = "Fira Sans",
              fontface = "plain") +
    geom_text(data = df_consumption %>% filter(continent == "Oceania") %>% summarize(pos_cont = unique(pos_cont)),
              aes(1, pos_cont,
                  label = continent,
                  color = continent,
                  color = after_scale(colorspace::darken(color, .3))),
              family = "Fira Sans",
              fontface = "bold",
              size = 6.2,
              lineheight = .9,
              hjust = .45,
              vjust = .5) +
    geom_text(data = df_consumption %>% filter(continent != "Oceania") %>% group_by(continent) %>% summarize(pos_cont = unique(pos_cont)),
              aes(1, pos_cont,
                  label = continent,
                  color = continent,
                  color = after_scale(colorspace::darken(color, .3))),
              family = "Fira Sans",
              fontface = "bold",
              size = 8.7,
              lineheight = .9,
              hjust = .5,
              vjust = .5) +
    coord_polar(theta = "y") +
    scale_x_continuous(limits = c(0, 1.9)) +
    scale_color_carto_d(palette = "Peach", direction = -1, guide = F) +
    scale_fill_carto_d(palette = "Peach", direction = -1, guide = F) +
    scale_alpha(range = c(.3, 1), guide = F) +
    scale_size(range = c(.7, 14), guide = F)

plot_consumption <-
  ggdraw(plot_c) +
  draw_image(here::here("img", "spoon_birthday_mod.png"),
             x = .5, y = .5013,
             hjust = .5, vjust = .5,
             width = 0.31, height = 0.31)
```


## CO2 Emissions

```{r plot-emission}
df_emmission <-
  df_food_cont %>%
  arrange(cont_emmission, count_emmission) %>%
  mutate(
    pos = cumsum(count_emmission),
    pos = if_else(!is.na(lag(pos)), pos - ((pos - lag(pos)) / 2), pos / 2),
    angle = 90 - 360 * (pos - 0.5),
    hjust = if_else(angle > 90, 0, 1),
    angle = ifelse(angle > 90, angle + 180, angle),
    label_big = if_else(
      country %in% (top_frac(df_food_cont, n = .5, wt = count_emmission) %>% pull(country)),
      country, NA_character_
    ),
    label_small = if_else(
      country %in% (top_frac(df_food_cont, n = .5, wt = -count_emmission) %>% pull(country)),
      country, NA_character_
    )
  ) %>%
  mutate(continent = fct_reorder(factor(continent), -cont_emmission)) %>%
  mutate(country = fct_reorder2(factor(country), as.numeric(continent), count_emmission, .desc = F)) %>%
  group_by(continent) %>%
  arrange(count_emmission) %>%
  mutate(
    alpha = count_emmission / max(count_emmission),
    pos_cont = min(pos) + (max(pos) - min(pos)) / 2,
    angle_cont = 90 - 360 * (pos_cont - 0.5),# / n(),
    hjust_cont = if_else(angle_cont > 90, 0, 1),
    angle_cont = ifelse(angle_cont > 90, angle_cont + 180, angle_cont)
  )

plot_e <-
  df_emmission %>%
  ggplot(aes(1, count_emmission)) +
    geom_col(
      aes(
        fill = continent,
        alpha = alpha,
        #color = after_scale(colorspace::darken(fill, .2)),
        fill = after_scale(colorspace::lighten(fill, .3))
      ),
      color = "white",
      size = .5
    ) +
    geom_col(
      aes(fill = continent,
          color = continent),
      width = .4,
      size = .8
    ) +
    geom_rect(
      xmin = -Inf, xmax = .8,
      ymin = -Inf, ymax = Inf,
      fill = "white"
    ) +
    geom_text(aes(1.475, pos,
                  label = label_big,
                  color = continent,
                  color = after_scale(colorspace::darken(color, .3)),
                  alpha = sqrt(alpha),
                  angle = angle,
                  hjust = hjust,
                  size = count_emmission^2),
              family = "Fira Sans",
              fontface = "bold") +
    geom_text(aes(1.475, pos,
                  label = label_small,
                  color = continent,
                  color = after_scale(colorspace::darken(color, .3)),
                  alpha = sqrt(alpha),
                  angle = angle,
                  hjust = hjust,
                  size = count_emmission^2),
              family = "Fira Sans",
              fontface = "plain") +
    geom_text(data = df_emmission %>% filter(continent == "Oceania") %>% summarize(pos_cont = unique(pos_cont)),
              aes(1, pos_cont,
                  label = continent,
                  color = continent,
                  color = after_scale(colorspace::darken(color, .3))),
              family = "Fira Sans",
              fontface = "bold",
              size = 8.2,
              lineheight = .9,
              hjust = .45,
              vjust = .5) +
    geom_text(data = df_emmission %>% filter(continent != "Oceania") %>% group_by(continent) %>% summarize(pos_cont = unique(pos_cont)),
              aes(1, pos_cont,
                  label = continent,
                  color = continent,
                  color = after_scale(colorspace::darken(color, .3))),
              family = "Fira Sans",
              fontface = "bold",
              size = 8.7,
              lineheight = .9,
              hjust = .5,
              vjust = .5) +
    coord_polar(theta = "y") +
    scale_x_continuous(limits = c(0, 1.9)) +
    scale_color_carto_d(palette = "TealGrn", direction = -1, guide = F) +
    scale_fill_carto_d(palette = "TealGrn", direction = -1, guide = F) +
    scale_alpha(range = c(.3, 1), guide = F) +
    scale_size(range = c(.7, 14), guide = F)

plot_emmission <-
  ggdraw(plot_e) +
  draw_image(here::here("img", "co2_mod.png"),
             x = .5007, y = .5014,
             hjust = .5, vjust = .5,
             width = 0.315, height = 0.315)
```

## Combined Panel

```{r panel, fig.width = 40, fig.height = 26.8}
p_consumption <-
  plot_consumption +
  theme(plot.margin = margin(0, -160, 0, 0))

p_emmission <-    
  plot_emmission +
  theme(plot.margin = margin(0, 0, 0, -160))

p_consumption + p_emmission +
  plot_annotation(title = "Food Carbon Footprint Index 2018",
                  subtitle = "Global comparison of different diets in terms of <span style='color:#dd4840;'><b>Average Consumption</b> (kg/person/year)</span> of both animal and non-animal products<br>as well as <span style='color:#2f7091;'><b>Carbon Emissions</b> (kg CO<sub>2</sub>/person/year)</span> per continent and country. Font size and color intensity indicate each country's<br>estimate with <b>countries printed in bold</b> belonging to the upper 50% of consumers and CO<sub>2</sub> emissioners, respectively.",
                  caption = "Visualization by Cédric Scherer  •  Data by Food and Agriculture Organization of the United Nations (FAO) via nu3  •  Icons by FreePik")

ggsave(here::here("plots", "2020_08", "2020_08_Carbon_Foodprint.pdf"),
       width = 40, height = 26.8, device = cairo_pdf)
```


***

```{r session-info}
sessionInfo()
```
