---
title: "TidyTuesday 2020/34 - Extinct Plants by IUCN Red List"
author: "Cedric Scherer"
date: "17th of August 2020"
output:
  html_document:
    theme: paper
    highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.showtext = T, fig.retina = 1)
```

```{r prep, message=FALSE}
## packages
library(tidyverse)
library(ggtext)
library(colorspace)
library(ragg)
library(patchwork)
library(cowplot)
library(pdftools)

theme_set(theme_void(base_family = "Playfair Display", base_size = 16))

theme_update(
  axis.text = element_blank(),
  legend.position = "none",
  strip.text = element_text(size = 11, color = "grey30", face = "italic", margin = margin(0, 0, 2, 0)), 
  panel.spacing = unit(0, "lines"),
  plot.title = element_text(family = "Neutraface 2 Display Titling", size = 44, color = "grey30", 
                            hjust = .5, margin = margin(0, 0, 10, 0)),
  plot.subtitle = element_text(size = 44, color = "grey60", face = "italic", 
                               hjust = .5, margin = margin(0, 0, 50, 0)),
  plot.caption = element_text(color = "grey60", size = 11, face = "italic", 
                              hjust = .5, margin = margin(15, 0, 0, 0)),
  plot.margin = margin(70, 70, 35, 70),
  plot.background = element_rect(color = "black", fill = "#F1F5F7", size = 3)
)
```


```{r data}
df_iucn <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/plants.csv') %>% 
  mutate(group = if_else(group == "Ferns and Allies", "Ferns & Allies", group))
```

```{r data-prep}
df_iucn_threat <- 
  df_iucn %>%
  pivot_longer(
    cols = threat_AA:threat_GE,
    names_to = "threat",
    values_to = "threathened"
  ) %>% 
  replace_na(list(threathened = 0)) %>% 
  mutate(
    id = fct_rev(factor(threat)),
    id = as.numeric(id) / 2 + 7
  ) %>%
  dplyr::select(binomial_name, group, continent, type = threat, id, case = threathened, year_last_seen) %>% 
  unique() %>% 
  complete(nesting(
    continent, group, binomial_name, year_last_seen), 
    id = seq(7, 14, by = .25), fill = list(case = 0)
  ) %>% 
  mutate(
    base = if_else((id %% .5 == 0 & id %in% seq(7.5, 12.5, by = .5)), .6, 0),
    case = if_else(case == 1, .6, case)
  )

df_iucn_action <-
  df_iucn %>% 
  pivot_longer(
    cols = action_LWP:action_EA,
    names_to = "action",
    values_to = "actioned"
  )  %>% 
  replace_na(list(actioned = 0)) %>% 
  mutate(id = as.numeric(factor(action))) %>%
  dplyr::select(binomial_name, group, continent, type = action, id, case = actioned, year_last_seen) %>% 
  unique() %>% 
  complete(nesting(
    continent, binomial_name, group, year_last_seen),
    id = seq(0, 6, by = .5), fill = list(case = 0)
  ) %>% 
  mutate(base = if_else((id %% 1 == 0 & id %in% 1:5), 1, 0))

df_iucn_long <-
  df_iucn_action %>% 
  bind_rows(df_iucn_threat) %>% 
  mutate(
    type = str_sub(type, 1, 6),
    year_last_seen = if_else(is.na(year_last_seen), "unknown", year_last_seen),
    year_last_seen = fct_relevel(factor(year_last_seen), "Before 1900", after = 0),
    group = factor(group)
  ) %>% 
  group_by(continent, binomial_name, group, year_last_seen, id, type) %>% 
  summarize(case = max(case), base = max(base))

pal <- c(
  "Before 1900" = "#9FA651", 
  "1900-1919" = "#799447", 
  "1920-1939" = "#4F7E35", 
  "1940-1959" = "#2A6B2A",
  "1960-1979" = "#4C8B64", 
  "1980-1999" = "#5C9F8C", 
  "2000-2020" = "#6BB2B2", 
  "unknown" = "#68696A"
)

shapes <- c(
  "Algae" = 24, 
  "Conifer" = 25, 
  "Cycad" = 23, 
  "Ferns & Allies" = 22, 
  "Flowering Plant" = 21, 
  "Mosses" = 8
)
```


```{r plants-based-on-Jakes-flowers}
plot_plant <- function(data, shape) {
  ggplot(
    data = data,
    aes(
        x = id, y = case, 
        fill = year_last_seen, 
        group = year_last_seen
      )
    ) +
    ## base leaves/roots
    geom_area(
      aes(y = base), 
      position = position_dodge(), 
      size = 0, fill = "grey89"
    ) +
    ## colored leaves
    geom_area(
      data = data %>% filter(id < 7), 
      aes(fill = year_last_seen), 
      position = position_dodge(), 
      size = 0
    ) +
    ## colored roots
    geom_area(
      data = data %>% filter(id > 7), 
      aes(
        fill = year_last_seen, 
        fill = after_scale(darken(fill, .3))
      ), 
      position = position_dodge(), 
      size = 0
    ) +
    ## remove part of leaves/roots
    geom_point(
      data = tibble(x = 0, y = 0), 
      aes(x, y), 
      inherit.aes = F, color = "#F1F5F7", size = 7
    ) +
    ## base stems
    geom_linerange(
      aes(ymin = 0, ymax = base - .3), 
      color = "grey79", size = .1, alpha = .5
    ) +
    ## colored stems
    geom_linerange(
      aes(
        ymin = 0, ymax = case - .3, 
        color = year_last_seen#, 
        #color = after_scale(darken(color, .3))
      ), 
      size = .2
    ) +
    ## white vessils leaves
    geom_linerange(
      data = data %>% filter(id < 7),
      aes(
        ymin = .184, ymax = case - .3
        
      ), 
      color = "white",
      size = .2
    ) +
    coord_polar(start = 4.92, clip = "off") +
    scale_y_continuous(limits = c(0, 1.15), expand = c(0, 0)) +
    scale_color_manual(values = pal) +
    scale_fill_manual(values = pal) +
    scale_shape_manual(values = shape) +
    scale_alpha_manual(values = c(1, .5))
}
```


## Poster Version per Continent

```{r facets-no-legend}
flower_facet <- function(cont, h) {
  d <- 
    df_iucn_long %>% 
    filter(continent == cont)
    
  s <- shapes[as.numeric(unique(d$group))]
  
  cont_trim <- str_remove(cont, "\\s")
  
  p <- plot_plant(data = d, shape = s) +
    ## plant group indicator
    geom_point(
      aes(
        x = 3, y = 1.15, 
        shape = group, 
        color = year_last_seen,
        fill = year_last_seen
      ), 
      inherit.aes = F, size = 2.5, stroke = .2
    ) + 
    facet_wrap(~binomial_name, labeller = label_wrap_gen(10), ncol = 13) +
    labs(
      title = "Plants in Danger",
      subtitle = glue::glue("— **{cont}** —"),
      caption = "Visualization: Cédric Scherer  • Idea: Florent Lavergne  •  Data: IUCN Red List"
    ) +
    theme(plot.subtitle = element_markdown()) +
    ggsave(here::here("plots", "2020_34", glue::glue("2020_34_ExtinctPlants_1_poster_{cont_trim}.pdf")),
            width = 25, height = h, device = cairo_pdf, limitsize = F)
}

p1 <- flower_facet("Africa", 39.44)
p2 <- flower_facet("Asia", 14.21)
p3 <- flower_facet("Europe", 5.8)
p4 <- flower_facet("North America", 18.41)
p5 <- flower_facet("Oceania", 10)
p6 <- flower_facet("South America", 18.41)
```


## Poster Version with Legend

```{r legend}
leg_a <-
  tibble(
    x = 0,
    y = rev(seq(0, 1, length.out = 8)),
    id = factor(levels(df_iucn_long$year_last_seen), 
                levels = levels(df_iucn_long$year_last_seen))
  ) %>% 
  mutate(hjust = if_else(as.numeric(id) %% 2 == 0, 1, 0), 
         xlab = if_else(as.numeric(id) %% 2 == 0, -.4, .4)) %>% 
  ggplot(aes(x, y, color = id)) +
    geom_point(size = 15) +
    geom_text(
      aes(x = xlab, label = str_to_title(id), hjust = hjust),
      family = "Playfair Display",
      color = "grey30",
      size = 3.5,
      fontface = "italic"
    ) +
    annotate(
      "text", x = .05, y = 1.2, 
      label = "Year Last Seen",
      family = "Playfair Display",
      color = "grey30",
      size = 4.7, 
      fontface = "bold"
    ) +
    scale_x_continuous(limits = c(-1.3, 1.3)) +
    scale_y_continuous(limits = c(-.3, 1.3)) +
    scale_color_manual(values = pal)

leg_b <-
  tibble(
    x = 0,
    y = rev(seq(0, 1, length.out = 6)),
    id = factor(levels(df_iucn_long$group))
  ) %>% 
  ggplot(aes(x, y, shape = id)) +
    geom_point(size = 6, color = "grey30", fill = "grey30") +
    geom_text(
      aes(label = str_to_title(id)),
      family = "Playfair Display",
      color = "grey30",
      size = 3.5, 
      fontface = "italic",
      hjust = 0,
      nudge_x = .3
    ) +
    annotate(
      "text", x = .3, y = 1.2, 
      label = "Plant Group",
      family = "Playfair Display",
      color = "grey30",
      size = 4.7, 
      fontface = "bold"
    ) +
    scale_x_continuous(limits = c(-.1, 1.1)) +
    scale_y_continuous(limits = c(-.3, 1.3)) +
    scale_shape_manual(values = shapes)

df <- 
  df_iucn_long  %>% 
  filter(binomial_name == "Astragalus nitidiflorus") %>% 
  mutate(
    label = case_when(
      ## actions
      id == 1 ~ "Education & Awareness",
      id == 2 ~ "Law & Policy",
      id == 3 ~ "Land & Water Protection",
      id == 4 ~ "Research & Monitoring",
      id == 5 ~ "Species Management",
      ## threats
      id == 12.5 ~ "Agriculture & Aquaculture",
      id == 12 ~ "Biological Resource Use",
      id == 11.5 ~ "Climate Change",
      id == 11 ~ "Energy Production & Mining",
      id == 10.5 ~ "Geological Events",
      id == 10 ~ "Human Intrusions",
      id == 9.5 ~ "Invasive Species",
      id == 9 ~ "Natural System Modifications",
      id == 8.5 ~ "Pollution",
      id == 8 ~ "Residential & Commercial Development",
      id == 7.5 ~ "Transportation Corridor"
    ),
    hjust = case_when(
      id %in% c(1, 2, seq(10.5, 12.5, by = .5)) ~ 1,
      id %in% c(4, 5, seq(7.5, 9.5, by = .5)) ~ 0,
      TRUE ~ .5
    ),
    nudge = case_when(
      id %in% c(1:5) ~ .05,
      id %in% c(9, 11) ~ .05,
      id %in% c(9.5, 10.5) ~ .1,
      id == 10 ~ .17,
      TRUE ~ .02
    )
  )

leg_c <- 
  plot_plant(df, shape = 21) +
  geom_text(
    aes(y = base + nudge, label = label, hjust = hjust),
    family = "Playfair Display",
    fontface = "italic",
    color = "grey30",
    size = 2.8
  ) +
  geom_text(
    data = tibble(x = c(3, 10), y = c(1.3, 1.1), 
                  label = c("Current Actions", "Extinction Threats")),
    aes(x, y, label = label), inherit.aes = F,
    family = "Playfair Display",
    fontface = "bold",
    color = "grey30",
    size = 4.7,
    vjust = 0
  ) +
  scale_y_continuous(limits = c(0, 1.3), expand = c(0, 0))

path <- here::here("plots", "2020_34", "2020_34_ExtinctPlants_2_legend")

(leg_a + leg_b + leg_c &
  theme(plot.background = element_rect(color = "#F1F5F7", fill = "#F1F5F7"), 
        plot.margin = margin(0, 20, 0, 0))) +
  plot_layout(widths = c(.52, .38, 1)) +
  ggsave(glue::glue("{path}.pdf"), width = 10, height = 4, device = cairo_pdf)

## convert for import
pdf_convert(pdf = glue::glue("{path}.pdf"), format = "png", dpi = 750, 
            filenames = glue::glue("{path}.png"))
```


```{r facets-legend}
flower_facet_legend <- function(cont, h, x, y, w) {
  ## cont: continent
  ## h: height in ggsave
  ## x: position legend horizontally
  ## y: position legend vertically
  ## w: width (size) legend
  
  d <- 
    df_iucn_long %>% 
    filter(continent == cont)
    
  s <- shapes[as.numeric(unique(d$group))]
  
  cont_trim <- str_remove(cont, "\\s")
  
  p <- plot_plant(data = d, shape = s) +
    ## plant group indicator
    geom_point(
      aes(
        x = 3, y = 1.15, 
        shape = group, 
        color = year_last_seen,
        fill = year_last_seen
      ), 
      inherit.aes = F, size = 2.5, stroke = .2
    ) + 
    facet_wrap(~binomial_name, labeller = label_wrap_gen(10), ncol = 8) +
    labs(
      title = "Plants in Danger",
      subtitle = glue::glue("— {cont} —"),
      caption = "Visualization: Cédric Scherer  • Idea: Florent Lavergne  •  Data: IUCN Red List"
    )
    
   ggdraw(p) +
     draw_image(glue::glue("{path}.png"), x, y, width = w, hjust = .5, vjust = .5) +
     ggsave(here::here("plots", "2020_34", glue::glue("2020_34_ExtinctPlants_2_poster_legend_{cont_trim}.pdf")),
            width = 20, height = h, device = cairo_pdf, limitsize = F)
}

p1 <- flower_facet_legend("Africa", 75.8, .8, .029, .33)
p2 <- flower_facet_legend("Asia", 24.13, .8, .09, .33)
p3 <- flower_facet_legend("Europe", 8.638, .8, .26, .33)
p4 <- flower_facet_legend("North America", 34.46, .8, .065, .33)
p5 <- flower_facet_legend("Oceania", 16.4, .85, .13, .27)
p6 <- flower_facet_legend("South America", 31.9, .8, .07, .33)
```


## Stand-alone Legend

```{r}
## standalone legend
(leg_a + leg_b + leg_c &
  theme(plot.background = element_rect(color = "#F1F5F7", fill = "#F1F5F7"), 
        plot.margin = margin(15, 35, 5, 15),
        plot.title = element_text(size = 30, margin = margin(t = 15, b = 5)),
        plot.subtitle = element_text(size = 15, margin = margin(b = 0)),
        plot.caption = element_text(size = 9, margin = margin(t = 0, b = 15)))) +
  plot_annotation(
    title = "Plants in Danger",
    subtitle = "— Extinct Plant Species Across the World —",
    caption = "Visualization: Cédric Scherer  • Idea: Florent Lavergne  •  Data: IUCN Red List"
  ) +
  plot_layout(widths = c(.52, .38, 1)) +
  ggsave(here::here("plots", "2020_34", "2020_34_ExtinctPlants_3_legend_standalone.pdf"), 
         width = 10, height = 5.7, device = cairo_pdf)
```


```{r convert-to-png}
## convert PDFs to PNGs
path <- here::here("plots", "2020_34")
pdfs <- list.files(path, pattern = "*.pdf")
setwd(path)
for(pdf in pdfs) {
  pdf_convert(pdf = glue::glue("{path}/{pdf}"), 
              format = "png", dpi = 250)
}
```

***

```{r session}
Sys.time()
git2r::repository()
sessionInfo()
```

