---
title: "TidyTuesday 2020/26 - Carribou Locations by Movebank"
author: "Cedric Scherer"
date: "28th of June 2020"
output:
  html_document:
    theme: paper
    highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.showtext = T, fig.retina = 1)
```

```{r prep, message=FALSE}
## packages
library(tidyverse)
library(raster)
library(sf)
library(rnaturalearth)
library(elevatr)
library(ggtext)
library(patchwork)
library(showtext)

font_add_google("Lilita One", "Lilita One")
font_add_google("Lora", "Lora")
showtext_auto()

## ggplot theme
theme_set(theme_void(base_family = "Lora"))

theme_update(
  plot.title = element_markdown(family = "Lilita One",
                                size = 24,
                                face = "bold",
                                hjust = 0),
  plot.caption = element_markdown(size = 12,
                                  lineheight = 1.4,
                                  hjust = 0,
                                  margin = margin(10, 0, 15, 0)),
  plot.margin = margin(rep(20, 4))
)
```

```{r data}
df_ind <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-23/individuals.csv')
df_loc <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-23/locations.csv')
```

```{r data-prep}
## projection
proj <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"


## location data incl. individual information as spatial object ########################################
## only for females tagged from 2000 on
sf_females <-
  df_loc %>%
  full_join(df_ind) %>%
  mutate(
    year = lubridate::year(timestamp),
    month = lubridate::month(timestamp),
    yday = lubridate::yday(timestamp)
  ) %>% filter(
    year > 2000,
    sex == "f"
  ) %>%
  st_as_sf(
    coords = c("longitude", "latitude"),
    crs = 4326
  ) %>%
  st_transform(crs = proj) %>%
  mutate(
    x = st_coordinates(.)[,1],
    y = st_coordinates(.)[,2],
    study_site = if_else(
      study_site == "Kennedy",
      "Kennedy\nSiding",
      study_site
    )
  )


## load and downscale treecover data ###################################################################
rds <- here::here("data", "2020_26", "canada_treecover_agg.Rds")

if (!file.exists(rds)) {
  raster_canada_120 <-
    raster(here::here("data", "2020_26", "Hansen_GFC2015_treecover2000_60N_120W.tif")) %>%
    aggregate(., fact = 25)

  raster_canada_130 <-
    raster(here::here("data", "2020_26", "Hansen_GFC2015_treecover2000_60N_130W.tif")) %>%
    aggregate(., fact = 25)

  ## turn rasters into single data frame
  df_canada <-
    raster_canada_120 %>%
    rasterToPoints() %>%
    as_tibble() %>%
    rename("tc" = contains("treecover")) %>%
    bind_rows(
      raster_canada_130 %>%
        rasterToPoints() %>%
        as_tibble() %>%
    rename("tc" = contains("treecover"))
    )

  write_rds(df_canada, path = rds)
} else {
  df_canada <- read_rds(rds)
}

## bounding box North America map  #####################################################################
bbox <- as(extent(-180, -42, 24, 85), 'SpatialPolygons')
crs(bbox) <- crs(proj)


## Low-res DEM data + hillshade for North America ######################################################
extent <- data.frame(x = c(-180, -42), y = c(24, 85))

dem <-
  get_elev_raster(
    extent,
    z = 4,
    prj = proj,
    clip = "bbox"
  )

dem@data@values <- dem@data@values * 10

slope <- terrain(dem, opt = 'slope')
aspect <- terrain(dem, opt = 'aspect')

df_hill <-
  hillShade(slope, aspect, 40, 270) %>%
  aggregate(fact = 2, method = "bilinear") %>%
  focal(w = matrix(1/9, nc = 3, nr = 3), mean) %>%
  rasterToPoints() %>%
  as_tibble() %>%
  mutate(layer = (layer * 10)^.8)

df_slope <-
  slope %>%
  aggregate(fact = 2, method = "bilinear") %>%
  rasterToPoints() %>%
  as_tibble() %>%
  ## invert the scale so that more slope is darker
  mutate(slope = 1 - slope)


## High-res DEM data + hillshade for study area ########################################################
extent_bc <- data.frame(x = c(-124.46, -119.45), y = c(54, 57.3))

dem_bc <-
  get_elev_raster(
    extent_bc,
    z = 7,
    prj = proj,
    clip = "bbox"
  )

dem_bc@data@values <- dem_bc@data@values * 10

slope_bc <- terrain(dem_bc, opt = 'slope')
aspect_bc <- terrain(dem_bc, opt = 'aspect')

df_hill_bc <-
  hillShade(slope_bc, aspect_bc, 40, 270) %>%
  aggregate(fact = 2, method = "bilinear") %>%
  focal(w = matrix(1/9, nc = 3, nr = 3), mean) %>%
  rasterToPoints() %>%
  as_tibble()

df_slope_bc <-
  slope_bc %>%
  aggregate(fact = 2, method = "bilinear") %>%
  rasterToPoints() %>%
  as_tibble() %>%
  ## invert the scale so that more slope is darker
  mutate(slope = 1 - slope)


## water: oceans, lakes, rivers ########################################################################
sf_oceans <-
  rnaturalearth::ne_download(scale = 10,
                             category = "physical",
                             type = "ocean",
                             returnclass = "sf") %>%
  st_transform(crs = proj) %>%
  st_make_valid() %>%
  st_crop(bbox)

sf_lakes <-
  rnaturalearth::ne_download(scale = 10,
                             category = "physical",
                             type = "lakes",
                             returnclass = "sf") %>%
  st_transform(crs = proj) %>%  
  st_make_valid() %>%
  st_crop(bbox)

# sf_rivers <-
#   rnaturalearth::ne_download(scale = 10,
#                              category = "physical",
#                              type = "rivers_lake_centerlines",
#                              returnclass = "sf") %>%
#   st_transform(crs = proj) %>%
#   st_crop(bbox)
```

```{r map-northamerica}
## box for Caribou study area
study_area <- as(extent(-124.37, -119.46, 54.05, 57.25, 57.25), 'SpatialPolygons')
crs(study_area) <- crs(proj)

## the key to a pretty map is merging the slope shade with the hillshade
m <-
  ggplot(df_hill) +
    geom_raster(
      aes(
        x, y,
        fill = layer,
        fill = after_scale(colorspace::darken(fill, .7, space = "HLS")),
        group = 1
      )
    ) +
    geom_raster(
      data = df_slope,
      aes(
        x, y,
        fill = slope,
        fill = after_scale(colorspace::darken(fill, .5, space = "HLS")),
        group = 2
      ),
      alpha = .6
    ) +
    geom_sf(
      data = sf_oceans,
      color = "transparent",
      fill = "#9bbaf3",
      alpha = .45
    ) +
    geom_sf(
      data = sf_lakes,
      color = "transparent",
      fill = "#9bbaf3", #dfe9fb
      alpha = .45
    ) +
    # geom_sf(
    #   data = sf_rivers,
    #   color = "#dfe9fb",
    #   size = .1
    # ) +
    geom_sf(
      data = st_as_sf(study_area),
      fill = NA,
      color = "black"
    ) +
    annotate(
      "text",
      x = -121.95, y = 58,
      label = "B + C",
      family = "Lilita One",
      size = 5.5
    ) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    rcartocolor::scale_fill_carto_c(
      palette = "Emrld",
      direction = -1,
      guide = F
    ) +
    labs(
      caption = '**A)** The Woodland Caribou, *Rangifer tarandus*, primarily occurs in North America and extends from Alaska to the northern United States and across all jurisdictions in Canada<br>except Nova Scotia, New Brunswick, Prince Edward Island, and Nunavut (Edmonds 1991, Thomas & Gray 2002). Individuals of the Northern Caribou, *Rangifer tarandus caribou*,<br>have been equipped with tracking collars to monitor their spatial distribution and recovery in British Columbia, Canada. The subspecies occurs in the mountainous and low-<br>land plateau areas of west-central and northern British Columbia and has distinct horizontal as well as vertical change in location when migrating (Heard & Vagt 1998).'
    )

ggsave(here::here("plots", "2020_26", "2020_26_Caribous_a_map.pdf"),
       width = 14.4, height = 12, device = cairo_pdf)
```


```{r plot-populations}
colors <-
  c("#C7237B", ## pink
    "#D72000", ## red
    "#EF7C12", ## orange
    "#1BB6AF", ## cyan
    "#4E9867", ## lime
    "#9E61CE", ## purple
    "#0076BB", ## blue
    "#F5D000"  ## yellow
  )

labels <-
  tribble(
    ~x, ~y, ~study_site, ~hjust,
    -122.55, 56.6, "Graham", 0, ## red
    -123.89, 56.11, "Scott", 0, ## yellow
    -122.3, 55.74, "Moberly", 0, ## lime
    -122.1, 55.48, "Burnt Pine", 0, ## pink
    -123.3, 55.06, "Kennedy\nSiding", .5, ## cyan
    -122.43, 54.8, "Hart Ranges", 1, ## orange
    -121.35, 55.32, "Quintette", .5, ## blue -> on top
    -120.4, 54.62, "Narraway", 0 ## purple
  )

set.seed(2020)

p <-
  sf_females %>%
  group_by(study_site) %>%
  sample_n(4000) %>%
  ungroup() %>%
  arrange(timestamp) %>%
  ggplot() +
    geom_raster(
      data = df_canada,
      aes(
        x, y,
        fill = tc,
        fill = after_scale(colorspace::darken(fill, .5, space = "HLS"))
      )
    ) +
    geom_sf(
      data = sf_lakes,
      color = "transparent",
      fill = "#dfe9fb"
    ) +
    geom_sf(
      color = "white",
      size = 1
    ) +
    geom_sf(
      aes(
        color = study_site,
        color = after_scale(colorspace::darken(color, .2, space = "HLS")),
        fill = after_scale(colorspace::lighten(color, .2, space = "HLS"))
      ),
      shape = 21,
      size = .65,
      stroke = .1
    ) +
    geom_text(
      data = labels,
      aes(
        x, y,
        label = study_site,
        color = study_site,
        color = after_scale(colorspace::lighten(color, .2, space = "HLS")),
        hjust = hjust
      ),
      family = "Lilita One",
      size = 7.5,
      lineheight = .8
    ) +
    coord_sf(
      xlim = c(-124.37, -119.46),
      ylim = c(54.05, 57.25)
    ) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    ggsci::scale_fill_material(palette = "light-green", guide = F) +
    scale_color_manual(values = colors, guide = F) +
    labs(
      caption = "**B)** Between 2001 and 2016, 219 Woodland Caribou have been tagged in 8 different populations. In total, 295,031<br>locations were successfully reported. Out of the 219 tracked individuals, 98% were female. The map shows a<br>sample of 4,000 locations per study site of all 215 cows. The green color gradient indicates the forest tree cover<br>in 2000 derived from Landsat images (Hansen *et al.* 2013)."
    )

ggsave(here::here("plots", "2020_26", "2020_26_Caribous_b_herds2.pdf"),
       width = 9.7, height = 12, device = cairo_pdf)
```

```{r plot-densities}
d <-
  sf_females %>%
  arrange(timestamp) %>%
  ggplot() +
    geom_raster(
      data = df_hill_bc,
      aes(
        x, y,
        fill = layer
      )
    ) +
    geom_raster(
      data = df_slope_bc,
      aes(
        x, y,
        fill = slope
      ),
      alpha = .4
    ) +
    geom_raster(
      data = df_canada %>% filter(tc < 75),
      aes(x, y),
      fill = "white",
      alpha = .2
    ) +
    geom_raster(
      data = df_canada %>% filter(tc >= 75),
      aes(x, y),
      fill = "#63ab63",
      alpha = .2
    ) +
    geom_sf(
      data = sf_lakes,
      color = "transparent",
      fill = "#dfe9fb"
    ) +
    stat_density2d(
      aes(
        x, y,
        alpha = ..level..,
        color = study_site,
        color = after_scale(colorspace::darken(color, .4, space = "HLS")),
        fill = after_scale(colorspace::lighten(color, .1, space = "HLS"))
      ),
      geom = "polygon",
      size = .2,
      n = 500,
      bins = 6,
      adjust = 3
    ) +
    coord_sf(
      xlim = c(-124.37, -119.46),
      ylim = c(54.05, 57.25)
    ) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    scale_color_manual(values = colors, guide = F) +
    scale_fill_gradient(low = "grey97", high = "grey50", guide = F) +
    scale_alpha_continuous(range = c(.3, .9), guide = F) +
    labs(
    #   title = "7 Years of Woodland Caribou Movement in Northern British Columbia"
      caption = "**C)** Northern Caribous concentrate their core range in forest habitats to obtain forage and shelter. They feed<br>primarily on lichens in winter that are found in high-elevation windswept ridges, subalpine and low-elevation<br>forests used by caribou (Jones *et al.* 2004). In summer, a wide variety of shrubs, forbs, and grasses serves as food<br>source. Shown are herd core areas, based on all cow locations. Green cells represent tree cover of 75% or more."
    )

ggsave(here::here("plots", "2020_26", "2020_26_Caribous_c_density.pdf"),
       width = 9.7, height = 12, device = cairo_pdf)
```


## final panel

```{r full-panel}
panel <-
  m + p + d +
  plot_layout(widths = c(.43, .29, .29)) +
  plot_annotation(
  title = 'Spatial patterns of South Peace Northern Caribou (*Rangifer tarandus caribou* pop. 15) in British Columbia, Canada',
  caption = 'Visualization: Cédric Scherer  •  Movement data: BC Ministry of Environment (2014) and Seip & Price (2019)  •  Elevation data: Amazon Web Services Terrain Tiles via {elevatr}  •  Forest cover data: Hansen **et al.** (2013)'
)

ggsave(here::here("plots", "2020_26", "2020_26_Caribous_full.pdf"),
       width = 34, height = 13, device = cairo_pdf)

## convert to png
pdfs <- list.files(here::here("plots", "2020_26"), pattern = "*.pdf")
setwd(here::here("plots", "2020_26"))
for(pdf in pdfs) {
  pdf_convert(pdf = here::here("plots", "2020_26", pdf),
              format = "png", dpi = 180)
}
```

***

```{r session}
Sys.time()
git2r::repository()
sessionInfo()
```
