---
title: "TidyTuesday 2021/27 - Animal Rescues by The Guardian"
author: "Cedric Scherer"
date: "4th of July 2021"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      dev = "ragg_png", res = 500, retina = 1)
```

```{r prep, message=FALSE, warning=FALSE}
## packages
library(tidyverse)
library(ggtext)
library(ggrepel)
library(patchwork)
library(systemfonts)

theme_set(theme_minimal(base_size = 19, base_family = "Girassol"))

theme_update(
  text = element_text(color = "grey12"),
  axis.title = element_blank(),
  axis.text.x = element_text(family = "Iosevka Curly"),
  axis.text.y = element_blank(),
  panel.grid.major.y = element_blank(),
  panel.grid.minor = element_blank(),
  plot.margin = margin(20, 5, 10, 10),
  plot.subtitle = element_textbox_simple(family = "Roboto Condensed", size = 14,
                                         lineheight = 1.6),
  plot.title.position = "plot",
  plot.caption = element_text(family = "Iosevka Curly", color = "#b40059", hjust = .5,
                              size = 10, margin = margin(35, 0, 0, 0))
)
```

## Data

```{r data}
df_animals <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-29/animal_rescues.csv')
```

```{r prep-data}
df_animals_agg <-
  df_animals %>% 
  mutate(
    animal_group_aggregated = case_when(
      str_detect(animal_group_parent, "Domestic|Livestock|Farm|Horse|Cow|Sheep|Goat|Lamb|Bull") ~ "Other Domestic Animals",
      animal_group_parent %in% c("Cat", "cat") ~ "Cats",
      animal_group_parent %in% c("Bird", "Budgie") ~ "Birds",
      animal_group_parent == "Dog" ~ "Dogs",
      animal_group_parent == "Fox" ~ "Foxes",
      TRUE ~ "Other Wild Animals"
    )
  ) %>% 
  count(cal_year, animal_group_aggregated) %>% 
  group_by(animal_group_aggregated) %>% 
  mutate(
    total = sum(n),
    current = n[which(cal_year == 2021)]
  ) %>% 
  ungroup() %>% 
  mutate(
    animal_group_aggregated = fct_reorder(animal_group_aggregated, total),
    animal_group_aggregated = fct_relevel(animal_group_aggregated, "Other Domestic Animals", after = 0),
    animal_group_aggregated = fct_relevel(animal_group_aggregated, "Other Wild Animals", after = 0)
  )

df_animals_labs <-
  df_animals_agg %>% 
  filter(cal_year == 2016) %>% 
  group_by(animal_group_aggregated) %>% 
  mutate(n = case_when(
    animal_group_aggregated == "Cats" ~ 320,
    animal_group_aggregated %in% c("Birds", "Dogs") ~ 135,
    TRUE ~ 55
  ))

df_animals_annotate <-
  df_animals_agg %>% 
  mutate(label = "\n\n← Number of Rescues in 2021 so far.") %>% 
  filter(cal_year == 2021 & animal_group_aggregated == "Cats")

df_animals_sum <-
  df_animals_agg %>% 
  filter(cal_year < 2021) %>% 
  group_by(cal_year) %>% 
  summarize(n = sum(n))
```

## Plot

```{r plot, fig.width=12, fig.height=20}
p1 <- 
  df_animals_sum %>% 
  ggplot(aes(cal_year, n)) +
    geom_col(aes(fill = factor(cal_year)), width = .85) +
    geom_col(
      data = df_animals_agg %>% filter(animal_group_aggregated == "Cats" & cal_year < 2021),
      aes(alpha = cal_year == 2020),
      fill = "white", width = .5
    ) +
    geom_text(
      data = df_animals_sum %>% 
        mutate(n_lab = if_else(cal_year %in% c(2009, 2020), paste0(n, "\nRescues"), as.character(n))),
      aes(label = n_lab), 
      family = "Iosevka Curly", size = 4.3, lineheight = .8, 
      nudge_y = 12, vjust = 0, color = "grey12", fontface = "bold"
    ) +
    geom_text(
      data = df_animals_agg %>% filter(animal_group_aggregated == "Cats" & cal_year < 2021) %>% 
        mutate(n_lab = if_else(cal_year %in% c(2009, 2020), paste0(n, "\nCats"), as.character(n))), 
      aes(label = n_lab), 
      family = "Iosevka Curly",
      color = "white", lineheight = .8, size = 4.3, 
      nudge_y = 12, vjust = 0, fontface = "bold"
    ) +
    geom_text(
      data = df_animals_agg %>% filter(animal_group_aggregated == "Cats" & cal_year < 2021),
      aes(y = -15, label = cal_year, color = factor(cal_year)), 
      family = "Iosevka Curly", size = 6, hjust = .5, vjust = 1
    ) +
    coord_cartesian(clip = "off") +
    scale_y_continuous(limits = c(-15, NA)) +
    scale_color_manual(values = c(rep("grey30", 11), "#b40059", "grey70"), guide = "none") +
    scale_fill_manual(values = c(rep("grey30", 11), "#b40059", "grey70"), guide = "none") +
    scale_alpha_manual(values = c(.25, .4), guide = "none") +
    labs(title = "Animal Rescues by London Fire Brigade Rise 20% in a <b style='color:#b40059'>Pandemic Year</b>",
         subtitle = "London firefighters encountered a surge in callouts to rescue animals in 2020, figures show. The London fire brigade (LFB) was involved in 758 such incidents – more than two a day. The number of rescues rose by 20% compared with 2019 when there were 604, with the biggest rise coming in the number of non-domestic animals rescued, according to the data.") +
    theme(
      plot.title = element_markdown(size = 28, margin = margin(5, 35, 25, 35), color = "black"),
      plot.subtitle = element_textbox_simple(margin = margin(5, 35, 15, 35)),
      panel.grid.major = element_blank(),
      axis.text.x = element_blank()
    )

p2 <- 
  df_animals_agg %>% 
  filter(cal_year < 2021) %>% 
  ggplot(aes(animal_group_aggregated, n)) +
  geom_col(
    aes(y = current), 
    fill = "grey85",
    position = position_dodge()
  ) +
  geom_col(
    aes(color = factor(cal_year), fill = after_scale(color)),
    position = position_dodge(), size = .001
  ) +
  geom_errorbar(
    data = filter(df_animals_agg, cal_year == 2021),
    aes(ymin = n, ymax = n), 
    color = "grey70", size = .8
  ) +
  geom_text(
    data = df_animals_agg %>% filter(animal_group_aggregated == "Cats" & cal_year < 2021) %>% 
      mutate(cal_year_lab = if_else(cal_year %in% c(2009, 2015, 2020), as.character(cal_year), "•")),
    aes(y = -8, label = cal_year_lab, color = factor(cal_year), size = cal_year_lab == "•"),
    position = position_dodge(width = .9), 
    family = "Iosevka Curly",  hjust = .5
  ) +
  ggrepel::geom_text_repel(
    data = df_animals_labs,
    aes(label = animal_group_aggregated),
    nudge_y = 10, family = "Girassol",
    size = 10, hjust = 0, color = "grey12",
    bg.color = "white", bg.r = .1 , segment.color = NA
  ) +
  geom_text(
    data = df_animals_annotate,
    aes(label = label),
    family = "Iosevka Curly", size = 5.4, color = "grey85", 
    nudge_y = 2, hjust = 0
  ) +
  coord_flip(clip = "off") +
  scale_x_discrete(expand = c(.09, .09)) + 
  scale_y_continuous(breaks = c(0, 25, 50, 75, 100, 125, 150, 200, 250, 300, 350), 
                     limits = c(-12, 355), sec.axis = dup_axis(name = "Number of Rescues")) +
  scale_color_manual(values = c(rep("grey30", 11), "#b40059", "grey70"), guide = "none") +
  scale_size_manual(values = c(3.8, 1.8), guide = "none") +
  labs(title = "Last Year, <b style='color:#b4005973'>Cats Accounted for 45%</b> of London Fire Brigade Animal Rescues, but the Biggest Proportional Increases were among Birds and Foxes.",
       subtitle = "Calls about distressed cats are the most common. Last year 338 were helped compared with 269 in 2019. Not all of them were stuck up trees: some managed to find themselves under floorboards, solar panels and fridges, and up telegraph poles and chimneys.<br><br>The number of incidents involving foxes attended by the LFB last year nearly doubled, from 32 rescues in 2019 to 61 in 2020. The Fox Project, a charity dedicated to protecting foxes in the south-east, said the increase in the number of rescues might be down to people’s growing sympathy towards the animals since the start of the pandemic.",
       caption = "Visualization: Cédric Scherer • Data: London Fire Brigade (london.gov; last update: 31/05/2021 19:00) • Text: The Guardian (modified)") +
  theme(plot.title = element_textbox_simple(size = 22, margin = margin(15, 35, 20, 35), color = "black"),
        plot.subtitle = element_textbox_simple(margin = margin(5, 35, 50, 35)))

p1 / p2 + plot_layout(heights = c(.55, 1))
```


```{r save-and-convert}
## convert PDF to PNG
path <- here::here("plots", "2021_27", "2021_27_AnimalRescues")

ggsave(glue::glue("{path}.pdf"), width = 12, height = 20, device = cairo_pdf)

pdftools::pdf_convert(pdf = glue::glue("{path}.pdf"), 
                      filenames = glue::glue("{path}.png"),
                      format = "png", dpi = 450)
```


***

```{r session}
Sys.time()
git2r::repository()
sessionInfo()
```
